-- ============================================================
-- 06_FreightForwarderQuoteTables.sql
-- Freight Forwarder catalog tables and quote tables
-- ============================================================

USE LicoresMaduoDB;
GO

-- ── Catalog tables ────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CURRENCIES')
    CREATE TABLE CURRENCIES (
        CUR_Id                INT IDENTITY(1,1) NOT NULL,
        CUR_CODE              NVARCHAR(3)   NOT NULL,
        CUR_DESCRIPTION       NVARCHAR(30)  NOT NULL,
        CUR_BNK_PURCHASE_RATE FLOAT         NULL,
        CUR_CUSTOMS_RATE      FLOAT         NULL,
        IS_Active             BIT           NOT NULL DEFAULT 1,
        Created_At            DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CURRENCIES PRIMARY KEY (CUR_Id),
        CONSTRAINT UQ_CURRENCIES_Code UNIQUE (CUR_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'LOADTYPES')
    CREATE TABLE LOADTYPES (
        LT_Id          INT IDENTITY(1,1) NOT NULL,
        LT_CODE        NVARCHAR(6)  NOT NULL,
        LT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_LOADTYPES PRIMARY KEY (LT_Id),
        CONSTRAINT UQ_LOADTYPES_Code UNIQUE (LT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PORT_OF_LOADING')
    CREATE TABLE PORT_OF_LOADING (
        PL_Id      INT IDENTITY(1,1) NOT NULL,
        PL_CODE    NVARCHAR(10) NOT NULL,
        PL_NAME    NVARCHAR(30) NOT NULL,
        PL_COUNTRY NVARCHAR(3)  NULL,
        IS_Active  BIT          NOT NULL DEFAULT 1,
        Created_At DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_PORT_OF_LOADING PRIMARY KEY (PL_Id),
        CONSTRAINT UQ_PORT_OF_LOADING_Code UNIQUE (PL_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SHIPPING_LINES')
    CREATE TABLE SHIPPING_LINES (
        SL_Id      INT IDENTITY(1,1) NOT NULL,
        SL_CODE    NVARCHAR(10) NOT NULL,
        SL_NAME    NVARCHAR(30) NOT NULL,
        IS_Active  BIT          NOT NULL DEFAULT 1,
        Created_At DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_SHIPPING_LINES PRIMARY KEY (SL_Id),
        CONSTRAINT UQ_SHIPPING_LINES_Code UNIQUE (SL_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SHIPPING_AGENT')
    CREATE TABLE SHIPPING_AGENT (
        SA_Id      INT IDENTITY(1,1) NOT NULL,
        SA_CODE    NVARCHAR(10) NOT NULL,
        SA_NAME    NVARCHAR(30) NOT NULL,
        IS_Active  BIT          NOT NULL DEFAULT 1,
        Created_At DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_SHIPPING_AGENT PRIMARY KEY (SA_Id),
        CONSTRAINT UQ_SHIPPING_AGENT_Code UNIQUE (SA_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ROUTES')
    CREATE TABLE ROUTES (
        ROU_Id          INT IDENTITY(1,1) NOT NULL,
        ROU_CODE        NVARCHAR(15) NOT NULL,
        ROU_DESCRIPTION NVARCHAR(30) NOT NULL,
        IS_Active       BIT          NOT NULL DEFAULT 1,
        Created_At      DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_ROUTES PRIMARY KEY (ROU_Id),
        CONSTRAINT UQ_ROUTES_Code UNIQUE (ROU_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CONTAINER_SPECS')
    CREATE TABLE CONTAINER_SPECS (
        CS_Id          INT IDENTITY(1,1) NOT NULL,
        CS_CODE        NVARCHAR(6)  NOT NULL,
        CS_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CONTAINER_SPECS PRIMARY KEY (CS_Id),
        CONSTRAINT UQ_CONTAINER_SPECS_Code UNIQUE (CS_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CONTAINER_TYPES')
    CREATE TABLE CONTAINER_TYPES (
        CT_Id              INT IDENTITY(1,1) NOT NULL,
        CT_CODE            NVARCHAR(6)  NOT NULL,
        CT_DESCRIPTION     NVARCHAR(50) NOT NULL,
        CT_CONTAINER_SPECS NVARCHAR(6)  NULL,
        CT_Cases           INT          NULL,
        CT_WGHT_Kilogram   INT          NULL,
        IS_Active          BIT          NOT NULL DEFAULT 1,
        Created_At         DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CONTAINER_TYPES PRIMARY KEY (CT_Id),
        CONSTRAINT UQ_CONTAINER_TYPES_Code UNIQUE (CT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ROUTES_BY_SHIPPING_AGENTS')
    CREATE TABLE ROUTES_BY_SHIPPING_AGENTS (
        RSA_Id            INT IDENTITY(1,1) NOT NULL,
        RSA_PORT          NVARCHAR(10) NOT NULL,
        RSA_SHIPPING_AGENT NVARCHAR(25) NOT NULL,
        RSA_ROUTE         NVARCHAR(10) NOT NULL,
        RSA_DAYS          SMALLINT     NULL,
        IS_Active         BIT          NOT NULL DEFAULT 1,
        Created_At        DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_ROUTES_BY_SHIPPING_AGENTS PRIMARY KEY (RSA_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OCEAN_FREIGHT_CHARGE_TYPES')
    CREATE TABLE OCEAN_FREIGHT_CHARGE_TYPES (
        OFCT_Id          INT IDENTITY(1,1) NOT NULL,
        OFCT_CODE        NVARCHAR(6)  NOT NULL,
        OFCT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active        BIT          NOT NULL DEFAULT 1,
        Created_At       DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_OCEAN_FREIGHT_CHARGE_TYPES PRIMARY KEY (OFCT_Id),
        CONSTRAINT UQ_OFCT_Code UNIQUE (OFCT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'INLAND_FREIGHT_CHARGE_TYPES')
    CREATE TABLE INLAND_FREIGHT_CHARGE_TYPES (
        IFCT_Id          INT IDENTITY(1,1) NOT NULL,
        IFCT_CODE        NVARCHAR(6)  NOT NULL,
        IFCT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active        BIT          NOT NULL DEFAULT 1,
        Created_At       DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_INLAND_FREIGHT_CHARGE_TYPES PRIMARY KEY (IFCT_Id),
        CONSTRAINT UQ_IFCT_Code UNIQUE (IFCT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'LCL_CHARGE_TYPES')
    CREATE TABLE LCL_CHARGE_TYPES (
        LCT_Id          INT IDENTITY(1,1) NOT NULL,
        LCT_CODE        NVARCHAR(6)  NOT NULL,
        LCT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active       BIT          NOT NULL DEFAULT 1,
        Created_At      DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_LCL_CHARGE_TYPES PRIMARY KEY (LCT_Id),
        CONSTRAINT UQ_LCT_Code UNIQUE (LCT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PRICE_TYPE')
    CREATE TABLE PRICE_TYPE (
        PT_Id          INT IDENTITY(1,1) NOT NULL,
        PT_CODE        NVARCHAR(6)  NOT NULL,
        PT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_PRICE_TYPE PRIMARY KEY (PT_Id),
        CONSTRAINT UQ_PRICE_TYPE_Code UNIQUE (PT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'AMOUNT_TYPE')
    CREATE TABLE AMOUNT_TYPE (
        AT_Id          INT IDENTITY(1,1) NOT NULL,
        AT_CODE        NVARCHAR(1)  NOT NULL,
        AT_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_AMOUNT_TYPE PRIMARY KEY (AT_Id),
        CONSTRAINT UQ_AMOUNT_TYPE_Code UNIQUE (AT_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CHARGE_ACTION')
    CREATE TABLE CHARGE_ACTION (
        CA_Id          INT IDENTITY(1,1) NOT NULL,
        CA_CODE        NVARCHAR(6)  NOT NULL,
        CA_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CHARGE_ACTION PRIMARY KEY (CA_Id),
        CONSTRAINT UQ_CHARGE_ACTION_Code UNIQUE (CA_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CHARGE_OVER')
    CREATE TABLE CHARGE_OVER (
        CO_Id          INT IDENTITY(1,1) NOT NULL,
        CO_CODE        NVARCHAR(6)  NOT NULL,
        CO_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CHARGE_OVER PRIMARY KEY (CO_Id),
        CONSTRAINT UQ_CHARGE_OVER_Code UNIQUE (CO_CODE)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CHARGE_PER')
    CREATE TABLE CHARGE_PER (
        CP_Id          INT IDENTITY(1,1) NOT NULL,
        CP_CODE        NVARCHAR(6)  NOT NULL,
        CP_DESCRIPTION NVARCHAR(25) NOT NULL,
        IS_Active      BIT          NOT NULL DEFAULT 1,
        Created_At     DATETIME     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_CHARGE_PER PRIMARY KEY (CP_Id),
        CONSTRAINT UQ_CHARGE_PER_Code UNIQUE (CP_CODE)
    );
GO

-- ── Freight Forwarders ────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FREIGHT_FORWARDERS')
    CREATE TABLE FREIGHT_FORWARDERS (
        FF_Id        INT IDENTITY(1,1) NOT NULL,
        FF_CODE      NVARCHAR(10)  NOT NULL,
        FF_NAME      NVARCHAR(50)  NOT NULL,
        FF_ADDRESS_1 NVARCHAR(100) NULL,
        FF_ADDRESS_2 NVARCHAR(100) NULL,
        FF_CITY      NVARCHAR(30)  NULL,
        FF_COUNTRY   NVARCHAR(3)   NULL,
        FF_PHONE_1   NVARCHAR(20)  NULL,
        FF_PHONE_2   NVARCHAR(20)  NULL,
        FF_EMAIL     NVARCHAR(100) NULL,
        FF_CONTACT   NVARCHAR(50)  NULL,
        FF_CURRENCY  NVARCHAR(3)   NULL,
        IS_Active    BIT           NOT NULL DEFAULT 1,
        Created_At   DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_FREIGHT_FORWARDERS PRIMARY KEY (FF_Id),
        CONSTRAINT UQ_FREIGHT_FORWARDERS_Code UNIQUE (FF_CODE)
    );
GO

-- ── Ocean Freight Quote tables ────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_OCEAN_FREIGHT_HEADER')
    CREATE TABLE FF_OCEAN_FREIGHT_HEADER (
        FQOH_Id          INT IDENTITY(1,1) NOT NULL,
        FQOH_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQOH_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQOH_START_DATE  DATE          NULL,
        FQOH_END_DATE    DATE          NULL,
        FQOH_REMARKS     NVARCHAR(200) NULL,
        Created_At       DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_FF_OCEAN_FREIGHT_HEADER PRIMARY KEY (FQOH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_OCEAN_FREIGHT_PORT')
    CREATE TABLE FF_OCEAN_FREIGHT_PORT (
        FQOP_Id          INT IDENTITY(1,1) NOT NULL,
        FQOP_Header_Id   INT           NOT NULL,
        FQOP_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQOP_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQOP_PORT        NVARCHAR(10)  NOT NULL,
        FQOP_REMARKS     NVARCHAR(200) NULL,
        CONSTRAINT PK_FF_OCEAN_FREIGHT_PORT PRIMARY KEY (FQOP_Id),
        CONSTRAINT FK_FQOP_Header FOREIGN KEY (FQOP_Header_Id) REFERENCES FF_OCEAN_FREIGHT_HEADER(FQOH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_OCEAN_FREIGHT_PORT_SLINE')
    CREATE TABLE FF_OCEAN_FREIGHT_PORT_SLINE (
        FQOPL_Id          INT IDENTITY(1,1) NOT NULL,
        FQOPL_Port_Id     INT           NOT NULL,
        FQOPL_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQOPL_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQOPL_PORT        NVARCHAR(10)  NOT NULL,
        FQOPL_SHIPLINE    NVARCHAR(10)  NOT NULL,
        FQOPL_ROUTE       NVARCHAR(15)  NULL,
        FQOPL_DAYS        INT           NULL,
        FQOPL_REMARKS     NVARCHAR(200) NULL,
        CONSTRAINT PK_FF_OCEAN_FREIGHT_PORT_SLINE PRIMARY KEY (FQOPL_Id),
        CONSTRAINT FK_FQOPL_Port FOREIGN KEY (FQOPL_Port_Id) REFERENCES FF_OCEAN_FREIGHT_PORT(FQOP_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES')
    CREATE TABLE FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES (
        FQOPLC_Id             INT IDENTITY(1,1) NOT NULL,
        FQOPLC_SLine_Id       INT           NOT NULL,
        FQOPLC_FORWARDER      NVARCHAR(10)  NOT NULL,
        FQOPLC_QUOTENUMBER    NVARCHAR(10)  NOT NULL,
        FQOPLC_PORT           NVARCHAR(10)  NOT NULL,
        FQOPLC_SHIPLINE       NVARCHAR(10)  NOT NULL,
        FQOPLC_CHARGE_TYPE    NVARCHAR(6)   NOT NULL,
        FQOPLC_CONTAINER_TYPE NVARCHAR(6)   NULL,
        FQOPLC_AMOUNT         DECIMAL(18,2) NULL,
        FQOPLC_CURRENCY       NVARCHAR(3)   NULL,
        CONSTRAINT PK_FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES PRIMARY KEY (FQOPLC_Id),
        CONSTRAINT FK_FQOPLC_SLine FOREIGN KEY (FQOPLC_SLine_Id) REFERENCES FF_OCEAN_FREIGHT_PORT_SLINE(FQOPL_Id)
    );
GO

-- ── Inland Freight Quote tables ───────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_INLAND_FREIGHT_HEADER')
    CREATE TABLE FF_INLAND_FREIGHT_HEADER (
        FQIH_Id          INT IDENTITY(1,1) NOT NULL,
        FQIH_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQIH_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQIH_START_DATE  DATE          NULL,
        FQIH_END_DATE    DATE          NULL,
        FQIH_REMARKS     NVARCHAR(200) NULL,
        Created_At       DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_FF_INLAND_FREIGHT_HEADER PRIMARY KEY (FQIH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_INLAND_FREIGHT_REGION')
    CREATE TABLE FF_INLAND_FREIGHT_REGION (
        FQIR_Id          INT IDENTITY(1,1) NOT NULL,
        FQIR_Header_Id   INT           NOT NULL,
        FQIR_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQIR_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQIR_REGION      NVARCHAR(20)  NOT NULL,
        CONSTRAINT PK_FF_INLAND_FREIGHT_REGION PRIMARY KEY (FQIR_Id),
        CONSTRAINT FK_FQIR_Header FOREIGN KEY (FQIR_Header_Id) REFERENCES FF_INLAND_FREIGHT_HEADER(FQIH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_INLAND_FREIGHT_REGION_TYPE')
    CREATE TABLE FF_INLAND_FREIGHT_REGION_TYPE (
        FQIRT_Id          INT IDENTITY(1,1) NOT NULL,
        FQIRT_Region_Id   INT           NOT NULL,
        FQIRT_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQIRT_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQIRT_REGION      NVARCHAR(20)  NOT NULL,
        FQIRT_CHARGE_TYPE NVARCHAR(6)   NOT NULL,
        FQIRT_AMOUNT_MIN  DECIMAL(18,2) NULL,
        FQIRT_AMOUNT_MAX  DECIMAL(18,2) NULL,
        FQIRT_CURRENCY    NVARCHAR(3)   NULL,
        CONSTRAINT PK_FF_INLAND_FREIGHT_REGION_TYPE PRIMARY KEY (FQIRT_Id),
        CONSTRAINT FK_FQIRT_Region FOREIGN KEY (FQIRT_Region_Id) REFERENCES FF_INLAND_FREIGHT_REGION(FQIR_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_INLAND_FREIGHT_REGION_TYPE_DET')
    CREATE TABLE FF_INLAND_FREIGHT_REGION_TYPE_DET (
        FQIRTD_Id             INT IDENTITY(1,1) NOT NULL,
        FQIRTD_RegionType_Id  INT           NOT NULL,
        FQIRTD_FORWARDER      NVARCHAR(10)  NOT NULL,
        FQIRTD_QUOTENUMBER    NVARCHAR(10)  NOT NULL,
        FQIRTD_REGION         NVARCHAR(20)  NOT NULL,
        FQIRTD_CHARGE_TYPE    NVARCHAR(6)   NOT NULL,
        FQIRTD_FROM           DECIMAL(18,4) NULL,
        FQIRTD_TO             DECIMAL(18,4) NULL,
        FQIRTD_PRICE          DECIMAL(18,6) NULL,
        FQIRTD_PRICE_TYPE     NVARCHAR(6)   NULL,
        FQIRTD_AMOUNT_MIN     DECIMAL(18,2) NULL,
        FQIRTD_AMOUNT_MAX     DECIMAL(18,2) NULL,
        CONSTRAINT PK_FF_INLAND_FREIGHT_REGION_TYPE_DET PRIMARY KEY (FQIRTD_Id),
        CONSTRAINT FK_FQIRTD_RegionType FOREIGN KEY (FQIRTD_RegionType_Id) REFERENCES FF_INLAND_FREIGHT_REGION_TYPE(FQIRT_Id)
    );
GO

-- ── LCL Quote tables ──────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_LCL_HEADER')
    CREATE TABLE FF_LCL_HEADER (
        FQLH_Id          INT IDENTITY(1,1) NOT NULL,
        FQLH_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQLH_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQLH_START_DATE  DATE          NULL,
        FQLH_END_DATE    DATE          NULL,
        FQLH_REMARKS     NVARCHAR(200) NULL,
        Created_At       DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_FF_LCL_HEADER PRIMARY KEY (FQLH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_LCL_PORT')
    CREATE TABLE FF_LCL_PORT (
        FQLP_Id          INT IDENTITY(1,1) NOT NULL,
        FQLP_Header_Id   INT           NOT NULL,
        FQLP_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQLP_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQLP_PORT        NVARCHAR(10)  NOT NULL,
        FQLP_REMARKS     NVARCHAR(200) NULL,
        CONSTRAINT PK_FF_LCL_PORT PRIMARY KEY (FQLP_Id),
        CONSTRAINT FK_FQLP_Header FOREIGN KEY (FQLP_Header_Id) REFERENCES FF_LCL_HEADER(FQLH_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_LCL_PORT_TYPE')
    CREATE TABLE FF_LCL_PORT_TYPE (
        FQLPT_Id          INT IDENTITY(1,1) NOT NULL,
        FQLPT_Port_Id     INT           NOT NULL,
        FQLPT_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQLPT_QUOTENUMBER NVARCHAR(10)  NOT NULL,
        FQLPT_PORT        NVARCHAR(10)  NOT NULL,
        FQLPT_CHARGE_TYPE NVARCHAR(6)   NOT NULL,
        FQLPT_AMOUNT_MIN  DECIMAL(18,2) NULL,
        FQLPT_AMOUNT_MAX  DECIMAL(18,2) NULL,
        FQLPT_CURRENCY    NVARCHAR(3)   NULL,
        CONSTRAINT PK_FF_LCL_PORT_TYPE PRIMARY KEY (FQLPT_Id),
        CONSTRAINT FK_FQLPT_Port FOREIGN KEY (FQLPT_Port_Id) REFERENCES FF_LCL_PORT(FQLP_Id)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_LCL_PORT_TYPE_DET')
    CREATE TABLE FF_LCL_PORT_TYPE_DET (
        FQLPTD_Id            INT IDENTITY(1,1) NOT NULL,
        FQLPTD_PortType_Id   INT           NOT NULL,
        FQLPTD_FORWARDER     NVARCHAR(10)  NOT NULL,
        FQLPTD_QUOTENUMBER   NVARCHAR(10)  NOT NULL,
        FQLPTD_PORT          NVARCHAR(10)  NOT NULL,
        FQLPTD_CHARGE_TYPE   NVARCHAR(6)   NOT NULL,
        FQLPTD_FROM          DECIMAL(18,4) NULL,
        FQLPTD_TO            DECIMAL(18,4) NULL,
        FQLPTD_PRICE         DECIMAL(18,6) NULL,
        FQLPTD_OVER          DECIMAL(18,2) NULL,
        FQLPTD_PRICE_TYPE    NVARCHAR(6)   NULL,
        FQLPTD_AMOUNT_MIN    DECIMAL(18,2) NULL,
        FQLPTD_AMOUNT_MAX    DECIMAL(18,2) NULL,
        CONSTRAINT PK_FF_LCL_PORT_TYPE_DET PRIMARY KEY (FQLPTD_Id),
        CONSTRAINT FK_FQLPTD_PortType FOREIGN KEY (FQLPTD_PortType_Id) REFERENCES FF_LCL_PORT_TYPE(FQLPT_Id)
    );
GO

-- ── Inland Additional Charges ─────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FF_INLAND_ADDITIONAL_CHARGES')
    CREATE TABLE FF_INLAND_ADDITIONAL_CHARGES (
        FQIA_Id          INT IDENTITY(1,1) NOT NULL,
        FQIA_FORWARDER   NVARCHAR(10)  NOT NULL,
        FQIA_CHARGE_TYPE NVARCHAR(6)   NOT NULL,
        FQIA_LOADTYPE    NVARCHAR(6)   NULL,
        FQIA_AMOUNT      DECIMAL(18,2) NULL,
        FQIA_ACTION      NVARCHAR(6)   NULL,
        FQIA_CHARGE_OVER NVARCHAR(6)   NULL,
        FQIA_CHARGE_PER  NVARCHAR(6)   NULL,
        FQIA_FROM        DECIMAL(18,4) NULL,
        FQIA_TO          DECIMAL(18,4) NULL,
        FQIA_AMOUNT_MIN  DECIMAL(18,2) NULL,
        FQIA_AMOUNT_MAX  DECIMAL(18,2) NULL,
        FQIA_CURRENCY    NVARCHAR(3)   NULL,
        Created_At       DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_FF_INLAND_ADDITIONAL_CHARGES PRIMARY KEY (FQIA_Id)
    );
GO
