-- ============================================================
-- 07_FreightForwarderSubmodules.sql
-- Activity Request and Aankoopbon catalog tables
-- ============================================================

USE LicoresMaduoDB;
GO

-- ── Activity Request catalog tables ──────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ACTIVITY_TYPE')
    CREATE TABLE ACTIVITY_TYPE    (AT_Id  INT IDENTITY(1,1) NOT NULL, AT_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY (AT_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BUDGET_ACTIVITIES')
    CREATE TABLE BUDGET_ACTIVITIES (BA_Id INT IDENTITY(1,1) NOT NULL, BA_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_BUDGET_ACTIVITIES PRIMARY KEY (BA_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DENIAL_REASONS')
    CREATE TABLE DENIAL_REASONS   (DR_Id  INT IDENTITY(1,1) NOT NULL, DR_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_DENIAL_REASONS PRIMARY KEY (DR_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ENTERTAINMENT_TYPE')
    CREATE TABLE ENTERTAINMENT_TYPE (ET_Id INT IDENTITY(1,1) NOT NULL, ET_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_ENTERTAINMENT_TYPE PRIMARY KEY (ET_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'STATUS_CODES')
    CREATE TABLE STATUS_CODES     (SC_Id  INT IDENTITY(1,1) NOT NULL, SC_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_STATUS_CODES PRIMARY KEY (SC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SPONSORING_TYPE')
    CREATE TABLE SPONSORING_TYPE  (ST_Id  INT IDENTITY(1,1) NOT NULL, ST_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_SPONSORING_TYPE PRIMARY KEY (ST_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FISCAL_YEARS')
    CREATE TABLE FISCAL_YEARS     (FY_Id  INT IDENTITY(1,1) NOT NULL, FY_Year INT NOT NULL, FY_StartDate DATE NULL, FY_EndDate DATE NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_FISCAL_YEARS PRIMARY KEY (FY_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'LICORES_GROUP')
    CREATE TABLE LICORES_GROUP    (LG_Id  INT IDENTITY(1,1) NOT NULL, LG_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_LICORES_GROUP PRIMARY KEY (LG_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'LOCATION_INFO')
    CREATE TABLE LOCATION_INFO    (LI_Id  INT IDENTITY(1,1) NOT NULL, LI_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_LOCATION_INFO PRIMARY KEY (LI_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'POS_CATEGORY')
    CREATE TABLE POS_CATEGORY     (PC_Id  INT IDENTITY(1,1) NOT NULL, PC_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_POS_CATEGORY PRIMARY KEY (PC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'POS_LEND_GIVE')
    CREATE TABLE POS_LEND_GIVE    (PLG_Id INT IDENTITY(1,1) NOT NULL, PLG_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_POS_LEND_GIVE PRIMARY KEY (PLG_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'POS_MATERIALS_STATUS')
    CREATE TABLE POS_MATERIALS_STATUS (PMS_Id INT IDENTITY(1,1) NOT NULL, PMS_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_POS_MATERIALS_STATUS PRIMARY KEY (PMS_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMER_NON_CLIENT')
    CREATE TABLE CUSTOMER_NON_CLIENT  (CNC_Id INT IDENTITY(1,1) NOT NULL, CNC_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CUSTOMER_NON_CLIENT PRIMARY KEY (CNC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMER_SALES_GROUP')
    CREATE TABLE CUSTOMER_SALES_GROUP (CSG_Id INT IDENTITY(1,1) NOT NULL, CSG_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CUSTOMER_SALES_GROUP PRIMARY KEY (CSG_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMER_SEGMENT_INFO')
    CREATE TABLE CUSTOMER_SEGMENT_INFO (CSI_Id INT IDENTITY(1,1) NOT NULL, CSI_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CUSTOMER_SEGMENT_INFO PRIMARY KEY (CSI_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMER_TARGET_GROUP')
    CREATE TABLE CUSTOMER_TARGET_GROUP (CTG_Id INT IDENTITY(1,1) NOT NULL, CTG_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CUSTOMER_TARGET_GROUP PRIMARY KEY (CTG_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'FACILITATORS_INFO')
    CREATE TABLE FACILITATORS_INFO (FI_Id INT IDENTITY(1,1) NOT NULL, FI_Description NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_FACILITATORS_INFO PRIMARY KEY (FI_Id));
GO

-- ── Activity catalog (CAT_*) tables ──────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_ADD_SPECS')
    CREATE TABLE CAT_ADD_SPECS       (CAS_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_ADD_SPECS PRIMARY KEY (CAS_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_APPAREL_TYPE')
    CREATE TABLE CAT_APPAREL_TYPE    (CAT_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_APPAREL_TYPE PRIMARY KEY (CAT_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_BAG_SPECS')
    CREATE TABLE CAT_BAG_SPECS       (CBS_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_BAG_SPECS PRIMARY KEY (CBS_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_BOTTLES')
    CREATE TABLE CAT_BOTTLES         (CB_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_BOTTLES PRIMARY KEY (CB_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_BRAND_SPECIFIC')
    CREATE TABLE CAT_BRAND_SPECIFIC  (CBR_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_BRAND_SPECIFIC PRIMARY KEY (CBR_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_CLOTHING_TYPE')
    CREATE TABLE CAT_CLOTHING_TYPE   (CCT_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_CLOTHING_TYPE PRIMARY KEY (CCT_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_COLORS')
    CREATE TABLE CAT_COLORS          (CC_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_COLORS PRIMARY KEY (CC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_CONTENT')
    CREATE TABLE CAT_CONTENT         (CCO_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_CONTENT PRIMARY KEY (CCO_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_COOLER_CAPACITY')
    CREATE TABLE CAT_COOLER_CAPACITY (CCC_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_COOLER_CAPACITY PRIMARY KEY (CCC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_COOLER_MODEL')
    CREATE TABLE CAT_COOLER_MODEL    (CCM_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_COOLER_MODEL PRIMARY KEY (CCM_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_COOLER_TYPE')
    CREATE TABLE CAT_COOLER_TYPE     (CCTY_Id INT IDENTITY(1,1) NOT NULL, CAT_Prefix NVARCHAR(10) NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_COOLER_TYPE PRIMARY KEY (CCTY_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_FILE_NAMES')
    CREATE TABLE CAT_FILE_NAMES      (CFN_Id INT IDENTITY(1,1) NOT NULL, File_Names NVARCHAR(100) NOT NULL, Display_Text NVARCHAR(100) NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_FILE_NAMES PRIMARY KEY (CFN_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_GENDER')
    CREATE TABLE CAT_GENDER          (CG_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_GENDER PRIMARY KEY (CG_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_GLASS_SERVING')
    CREATE TABLE CAT_GLASS_SERVING   (CGS_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_GLASS_SERVING PRIMARY KEY (CGS_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_INSURRANCE')
    CREATE TABLE CAT_INSURRANCE      (CI_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_INSURRANCE PRIMARY KEY (CI_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_LED')
    CREATE TABLE CAT_LED             (CL_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_LED PRIMARY KEY (CL_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_MAINT_MONTHS')
    CREATE TABLE CAT_MAINT_MONTHS    (CMM_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_MAINT_MONTHS PRIMARY KEY (CMM_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_MATERIALS')
    CREATE TABLE CAT_MATERIALS       (CM_Id  INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_MATERIALS PRIMARY KEY (CM_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_SHAPES')
    CREATE TABLE CAT_SHAPES          (CS2_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_SHAPES PRIMARY KEY (CS2_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_SIZES')
    CREATE TABLE CAT_SIZES           (CSZ_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_SIZES PRIMARY KEY (CSZ_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CAT_VAP_TYPE')
    CREATE TABLE CAT_VAP_TYPE        (CVT_Id INT IDENTITY(1,1) NOT NULL, CAT_Sel NVARCHAR(100) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_CAT_VAP_TYPE PRIMARY KEY (CVT_Id));
GO

-- ── Aankoopbon tables ─────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'VENDORS')
    CREATE TABLE VENDORS (
        VND_Id       INT IDENTITY(1,1) NOT NULL,
        VND_Code     NVARCHAR(6)   NOT NULL,
        VND_Name     NVARCHAR(100) NOT NULL,
        VND_Address_1 NVARCHAR(100) NULL,
        VND_Phone_1  NVARCHAR(25)  NULL,
        VND_Email    NVARCHAR(50)  NULL,
        VND_Contact  NVARCHAR(100) NULL,
        VND_CURR     NVARCHAR(3)   NULL,
        VND_CRIB     NVARCHAR(15)  NULL,
        VND_KVK      NVARCHAR(15)  NULL,
        VND_CASH     BIT           NULL,
        IS_Active    BIT           NOT NULL DEFAULT 1,
        Created_At   DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_VENDORS PRIMARY KEY (VND_Id),
        CONSTRAINT UQ_VENDORS_Code UNIQUE (VND_Code)
    );
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DEPARTMENTS')
    CREATE TABLE DEPARTMENTS (DP_Id INT IDENTITY(1,1) NOT NULL, DP_NAME NVARCHAR(15) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DP_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'EENHEDEN')
    CREATE TABLE EENHEDEN (EE_Id INT IDENTITY(1,1) NOT NULL, UnitCode NVARCHAR(10) NOT NULL, Omschrijving NVARCHAR(50) NULL, OmrekenFaktor DECIMAL(18,4) NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_EENHEDEN PRIMARY KEY (EE_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RECEIVERS')
    CREATE TABLE RECEIVERS (REC_Id INT IDENTITY(1,1) NOT NULL, REC_NAME NVARCHAR(30) NOT NULL, REC_ID_DOC NVARCHAR(15) NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_RECEIVERS PRIMARY KEY (REC_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REQUESTORS')
    CREATE TABLE REQUESTORS (REQ_Id INT IDENTITY(1,1) NOT NULL, REQ_NAME NVARCHAR(15) NOT NULL, REQ_EMAIL NVARCHAR(50) NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_REQUESTORS PRIMARY KEY (REQ_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REQUESTORS_VENDOR')
    CREATE TABLE REQUESTORS_VENDOR (RV_Id INT IDENTITY(1,1) NOT NULL, RS_REQUESTOR NVARCHAR(15) NOT NULL, RS_VENDOR NVARCHAR(6) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_REQUESTORS_VENDOR PRIMARY KEY (RV_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'COST_TYPE')
    CREATE TABLE COST_TYPE (CT_Id INT IDENTITY(1,1) NOT NULL, TC_NAME NVARCHAR(15) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_COST_TYPE PRIMARY KEY (CT_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'VEHICLE_TYPE')
    CREATE TABLE VEHICLE_TYPE (VT_Id INT IDENTITY(1,1) NOT NULL, VT_NAME NVARCHAR(15) NOT NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_VEHICLE_TYPE PRIMARY KEY (VT_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'VEHICLES')
    CREATE TABLE VEHICLES (VH_Id INT IDENTITY(1,1) NOT NULL, VH_LICENSE NVARCHAR(10) NOT NULL, VH_TYPE NVARCHAR(15) NULL, VH_MODEL NVARCHAR(15) NULL, IS_Active BIT NOT NULL DEFAULT 1, Created_At DATETIME NOT NULL DEFAULT GETUTCDATE(), CONSTRAINT PK_VEHICLES PRIMARY KEY (VH_Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'AB_PRODUCTS')
    CREATE TABLE AB_PRODUCTS (
        ABP_Id      INT IDENTITY(1,1) NOT NULL,
        ItemKode    NVARCHAR(20)  NOT NULL,
        Omschrijving NVARCHAR(100) NULL,
        VendorCode  NVARCHAR(6)   NULL,
        Cost_Type   NVARCHAR(15)  NULL,
        Eenheid     NVARCHAR(10)  NULL,
        IS_Active   BIT           NOT NULL DEFAULT 1,
        Created_At  DATETIME      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT PK_AB_PRODUCTS PRIMARY KEY (ABP_Id)
    );
GO
