-- ============================================================
-- 36 – FreightQuote LCL Port / PortType / Detail tables
-- ============================================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_LCL_PORT')
BEGIN
    CREATE TABLE FF_QUOTE_LCL_PORT (
        FQLCP_Id        INT IDENTITY(1,1) PRIMARY KEY,
        FQLCP_Header_Id INT          NOT NULL,
        FQLCP_PORT      NVARCHAR(10) NOT NULL,
        FQLCP_REMARKS   NVARCHAR(200) NULL,
        CONSTRAINT FK_FQLCP_Header FOREIGN KEY (FQLCP_Header_Id)
            REFERENCES FF_QUOTE_HEADER(FQH_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_LCL_PORT';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_LCL_PORT_TYPE')
BEGIN
    CREATE TABLE FF_QUOTE_LCL_PORT_TYPE (
        FQLCPT_Id          INT IDENTITY(1,1) PRIMARY KEY,
        FQLCPT_Port_Id     INT          NOT NULL,
        FQLCPT_CHARGE_TYPE NVARCHAR(6)  NOT NULL,
        FQLCPT_AMOUNT_MIN  DECIMAL(18,4) NULL,
        FQLCPT_AMOUNT_MAX  DECIMAL(18,4) NULL,
        FQLCPT_CURRENCY    NVARCHAR(3)  NULL,
        CONSTRAINT FK_FQLCPT_Port FOREIGN KEY (FQLCPT_Port_Id)
            REFERENCES FF_QUOTE_LCL_PORT(FQLCP_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_LCL_PORT_TYPE';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_LCL_PORT_TYPE_DET')
BEGIN
    CREATE TABLE FF_QUOTE_LCL_PORT_TYPE_DET (
        FQLCPTD_Id           INT IDENTITY(1,1) PRIMARY KEY,
        FQLCPTD_PortType_Id  INT           NOT NULL,
        FQLCPTD_FROM         DECIMAL(18,4) NULL,
        FQLCPTD_TO           DECIMAL(18,4) NULL,
        FQLCPTD_PRICE        DECIMAL(18,6) NULL,
        FQLCPTD_OVER         DECIMAL(18,4) NULL,
        FQLCPTD_PRICE_TYPE   NVARCHAR(6)   NULL,
        FQLCPTD_AMOUNT_MIN   DECIMAL(18,2) NULL,
        FQLCPTD_AMOUNT_MAX   DECIMAL(18,2) NULL,
        CONSTRAINT FK_FQLCPTD_PortType FOREIGN KEY (FQLCPTD_PortType_Id)
            REFERENCES FF_QUOTE_LCL_PORT_TYPE(FQLCPT_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_LCL_PORT_TYPE_DET';
END
