-- ============================================================
-- 37 – FreightQuote Ocean Port / SLine tables
--      + restructure Ocean Charge to link to SLine
-- ============================================================

-- 1. Drop existing Ocean Charge table if has old structure (Header FK)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'FF_QUOTE_OCEAN_CHARGE' AND COLUMN_NAME = 'FQOC_Header_Id')
BEGIN
    -- Drop constraints first
    DECLARE @cn NVARCHAR(256);
    SELECT @cn = CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME = 'FF_QUOTE_OCEAN_CHARGE' AND CONSTRAINT_TYPE = 'FOREIGN KEY';
    IF @cn IS NOT NULL EXEC('ALTER TABLE FF_QUOTE_OCEAN_CHARGE DROP CONSTRAINT ' + @cn);

    DROP TABLE FF_QUOTE_OCEAN_CHARGE;
    PRINT 'Dropped old FF_QUOTE_OCEAN_CHARGE';
END

-- 2. Ocean Port
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_OCEAN_PORT')
BEGIN
    CREATE TABLE FF_QUOTE_OCEAN_PORT (
        FQOP_Id        INT IDENTITY(1,1) PRIMARY KEY,
        FQOP_Header_Id INT           NOT NULL,
        FQOP_PORT      NVARCHAR(10)  NOT NULL,
        FQOP_REMARKS   NVARCHAR(200) NULL,
        CONSTRAINT FK_FQQOP_Header FOREIGN KEY (FQOP_Header_Id)
            REFERENCES FF_QUOTE_HEADER(FQH_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_OCEAN_PORT';
END

-- 3. Ocean Port Shipping Line
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_OCEAN_PORT_SLINE')
BEGIN
    CREATE TABLE FF_QUOTE_OCEAN_PORT_SLINE (
        FQOPS_Id            INT IDENTITY(1,1) PRIMARY KEY,
        FQOPS_Port_Id       INT          NOT NULL,
        FQOPS_SHIPPING_LINE NVARCHAR(10) NOT NULL,
        FQOPS_ROUTE         NVARCHAR(15) NULL,
        FQOPS_DAYS          INT          NULL,
        CONSTRAINT FK_FQQOPS_Port FOREIGN KEY (FQOPS_Port_Id)
            REFERENCES FF_QUOTE_OCEAN_PORT(FQOP_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_OCEAN_PORT_SLINE';
END

-- 4. Ocean Charge (now under SLine)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FF_QUOTE_OCEAN_CHARGE')
BEGIN
    CREATE TABLE FF_QUOTE_OCEAN_CHARGE (
        FQOC_Id             INT IDENTITY(1,1) PRIMARY KEY,
        FQOC_SLine_Id       INT           NOT NULL,
        FQOC_CHARGE_TYPE    NVARCHAR(6)   NOT NULL,
        FQOC_CONTAINER_TYPE NVARCHAR(6)   NULL,
        FQOC_AMOUNT         DECIMAL(18,4) NULL,
        FQOC_CURRENCY       NVARCHAR(3)   NULL,
        CONSTRAINT FK_FQQOC_SLine FOREIGN KEY (FQOC_SLine_Id)
            REFERENCES FF_QUOTE_OCEAN_PORT_SLINE(FQOPS_Id) ON DELETE CASCADE
    );
    PRINT 'Created FF_QUOTE_OCEAN_CHARGE (under SLine)';
END
