-- ============================================================
-- 42 – Seed REGIONS from REGIONS.xlsx
-- ============================================================

SET NOCOUNT ON;

MERGE REGIONS AS tgt
USING (VALUES
    ('AFR',   'AFRICA',                              'CF'),
    ('ARG',   'ARGENTINA',                           'AR'),
    ('ARMEN', 'ARGENTINA MEND',                      'AR'),
    ('ATMIT', 'AUSTRIA MITTEL',                      'AT'),
    ('ATNEU', 'AUSTRIA NEUS',                        'AT'),
    ('ATWAC', 'AUSTRIA WACHA',                       'AT'),
    ('AUSCO', 'AUSTRALIA SOUT',                      'AU'),
    ('AUST',  'AUSTRIA',                             'AT'),
    ('BAR',   'BARBADOS',                            'BB'),
    ('BEL',   'BELGUIM',                             'BE'),
    ('BRA',   'BRAZIL',                              'BR'),
    ('CAN',   'CANADA',                              'CA'),
    ('CANIA', 'CANADA NIAGARA',                      'CA'),
    ('CH',    'CHILE',                               'CL'),
    ('CHCAS', 'CHILE CASABLAN',                      'CL'),
    ('CHCEN', 'CHILE CENTRAL',                       'CL'),
    ('CHCOL', 'CHILE COLCHAGU',                      'CL'),
    ('CHLIM', 'CHILE LIMARI',                        'CL'),
    ('CHMAI', 'CHILE MAIPO',                         'CL'),
    ('CHMAU', 'CHILE MAULE',                         'CL'),
    ('CHPAT', 'CHILE PATAG.',                        'CL'),
    ('CHRAP', 'CHILE RAPEL',                         'CL'),
    ('CUR',   'CURACAO',                             'CW'),
    ('DOLX',  'LOCKBOX',                             'DO'),
    ('DOSJB', 'SA JUAN BAUTISTA',                    'DO'),
    ('ES08',  'D.O. PENEDES-PLA DE BAGES-ALELLA',    'ES'),
    ('ES11',  'D.O. JEREZ',                          'ES'),
    ('ES14',  'D.O. MONTILLA - MORILES',             'ES'),
    ('ES26',  'D.O. ARABAKO TACOLINA- LA RIOJA NAV', 'ES'),
    ('ES30',  'D.O. JUMILA - BULLAS - YECLA',        'ES'),
    ('ES47',  'D.O. RIBERO DEL DUERO - RUEDA',       'ES'),
    ('ESBAR', 'SPAIN BARCELONA',                     'ES'),
    ('ESBAS', 'SPAIN PAIS BASCO',                    'ES'),
    ('ESBIE', 'SPAIN BIERZO',                        'ES'),
    ('ESBUR', 'SPAIN BURGOS',                        'ES'),
    ('ESCAT', 'SPAIN CATALUN.',                      'ES'),
    ('ESCON', 'SPAIN C DE BAR',                      'ES'),
    ('ESLA',  'SPAIN LA MANCH',                      'ES'),
    ('ESMAD', 'SPAIN MADRID',                        'ES'),
    ('ESMON', 'SPAIN MONTSANT',                      'ES'),
    ('ESPEN', 'SPAIN PENEDES',                       'ES'),
    ('ESPLA', 'PLASENCIA',                           'ES'),
    ('ESPRI', 'SPAIN PRIORAT',                       'ES'),
    ('ESRIA', 'SPAIN RIAS BAI',                      'ES'),
    ('ESRIB', 'SPAIN RIB DUE',                       'ES'),
    ('ESRIO', 'SPAIN RIOJA',                         'ES'),
    ('ESRUE', 'SPAIN RUEDA',                         'ES'),
    ('ESSOM', 'SPAIN SOMONTANO',                     'ES'),
    ('ESVAL', 'SPAIN VALENCIA',                      'ES'),
    ('ESVLA', 'SPAIN VALLDOLID',                     'ES'),
    ('FR',    'FRANCE',                              'FR'),
    ('FRALS', 'FRANCE ALSACE',                       'FR'),
    ('FRARD', 'FRANCE ARDECHE',                      'FR'),
    ('FRBEA', 'FRANCE BEAUJOLAIS',                   'FR'),
    ('FRBLF', 'BLANQUEFORT',                         'FR'),
    ('FRBOR', 'FRANCE BORDEAUX',                     'FR'),
    ('FRBUR', 'FRANCE BOURGOGNE',                    'FR'),
    ('FRCHA', 'FRANCE CHAMPAGNE & NORTH',             'FR'),
    ('FRCOG', 'FRANCE COGNAC',                       'FR'),
    ('FRJUR', 'JURA',                                'FR'),
    ('FRLAN', 'FRANCE LANGUEDOC-ROUSSILLON',         'FR'),
    ('FRLOI', 'FRANCE LOIRE',                        'FR'),
    ('FRNOR', 'NORMANDIE',                           'FR'),
    ('FRPAR', 'PARIS',                               'FR'),
    ('FRPET', 'PETERSBACH',                          'FR'),
    ('FRPRO', 'FRANCE PROVENCE',                     'FR'),
    ('FRRHO', 'FRANCE RHONE',                        'FR'),
    ('FRSAN', 'SANCERRE',                            'FR'),
    ('FRSOU', 'FRANCE SOUTH',                        'FR'),
    ('FRSSP', 'COTES RHONE SUD PROVENCE',            'FR'),
    ('FRVDP', 'FRANCE VDP',                          'FR'),
    ('FRVDT', 'FRANCE VDT',                          'FR'),
    ('GER',   'GERMANY',                             'DE'),
    ('GERHE', 'GERMANY RHEINH',                      'DE'),
    ('GREEC', 'GREECE',                              'GR'),
    ('GUA',   'GUADALUPE',                           'GP'),
    ('IR',    'IRELAND',                             'IE'),
    ('IRE',   'IRELAND',                             'IE'),
    ('ISR',   'ISRAEL',                              'IL'),
    ('IT',    'ITALY',                               'IT'),
    ('ITFRA', 'FRANCESCOI',                          'IT'),
    ('ITORV', 'ITALY ORVIETO',                       'IT'),
    ('ITPIE', 'ITALY PIEDMONT',                      'IT'),
    ('ITPUG', 'ITALY PUGLIA',                        'IT'),
    ('ITSIC', 'ITALY SICELY',                        'IT'),
    ('ITTUS', 'ITALY TUSCANY',                       'IT'),
    ('ITVEN', 'ITALY VENETO',                        'IT'),
    ('ITVFG', 'VIA FORTE GAROFOLO',                  'IT'),
    ('JA',    'JAMAICA',                             'JM'),
    ('JAP',   'JAPAN',                               'JP'),
    ('MEX',   'MEXICO',                              'MX'),
    ('NEDAM', 'NEDERLAND ADAM',                      'NL'),
    ('NEHAW', 'NEW ZEALAND',                         'NZ'),
    ('NL',    'NETHERLANDS',                         'NL'),
    ('NLBA',  'BAARN',                               'NL'),
    ('NLBUS', 'BUSSUM',                              'NL'),
    ('NLDRA', 'DRACHTEN',                            'NL'),
    ('NLHL',  'HILVERSUM',                           'NL'),
    ('NY',    'NEW YORK',                            'US'),
    ('PL',    'POLAND',                              'PL'),
    ('PODOU', 'PORTUGAL DOURO',                      'PT'),
    ('POL',   'POLAND',                              'PL'),
    ('PORT',  'PORTUGAL',                            'PT'),
    ('PR',    'PUERTO RICO',                         'PR'),
    ('PRBAY', 'BAYAMON',                             'PR'),
    ('PTALE', 'PORTUGAL ALENT',                      'PT'),
    ('PTBAI', 'PORTUGAL BAIRR',                      'PT'),
    ('PTDAO', 'PORTUGAL DAO',                        'PT'),
    ('PTDOU', 'PORTUGAL DOURO',                      'PT'),
    ('PTLIS', 'PORTUGAL LISBOA',                     'PT'),
    ('PTPOR', 'PORTUGAL PORT',                       'PT'),
    ('PTVIN', 'PORT VINHO VER',                      'PT'),
    ('RUS',   'RUSSIA',                              'RU'),
    ('SA',    'SOUTH AFRICA',                        'ZA'),
    ('SOSTE', 'SOUTH AFRICA',                        'ZA'),
    ('SOW',   'SOUTH AFRICA W',                      'ZA'),
    ('SP',    'SPAIN',                               'ES'),
    ('SPAND', 'SPAIN ANDA',                          'ES'),
    ('UKLON', 'UK LONDON',                           'GB'),
    ('UKSCO', 'UK SCOTLAND',                         'GB'),
    ('USAOG', 'USA OREGON',                          'US'),
    ('USCAL', 'USA CALIFORNIA',                      'US'),
    ('USLIC', 'LONG ISLAND CITY',                    'US'),
    ('USMIA', 'US MIAMI',                            'US'),
    ('USNAP', 'USA NAPA VALLEY',                     'US'),
    ('USNOR', 'USA NO REGION',                       'US'),
    ('USPEN', 'USA PENNSYLVANIA',                    'US'),
    ('USSF',  'SAN FRANCISCO',                       'US'),
    ('USSON', 'USA SONOMA',                          'US'),
    ('USTEX', 'USA TEXAS',                           'US'),
    ('USWAS', 'U.S. WASHINGTON',                     'US'),
    ('VEN',   '2da DE LOS CORTIJOS DE LOURDES',      'VE'),
    ('ZAKL',  'KOELENHOF',                           'ZA'),
    ('ZW',    'ZWITSERLAND',                         'CH')
) AS src (REG_Code, REG_Name, REG_Country)
ON tgt.REG_Code = src.REG_Code
WHEN NOT MATCHED BY TARGET THEN
    INSERT (REG_Code, REG_Name, REG_Country, IsActive, CreatedAt)
    VALUES (src.REG_Code, src.REG_Name, src.REG_Country, 1, GETUTCDATE())
WHEN MATCHED THEN
    UPDATE SET
        REG_Name    = src.REG_Name,
        REG_Country = src.REG_Country;

PRINT CONCAT('REGIONS seed complete. Rows affected: ', @@ROWCOUNT);
GO
