USE LicoresMaduoDB;
GO

/* 
   Script 71: Recrear tabla CC_TARIFF_ITEMS según formato GS-2012 (Excel)
   Módulo: Cost Calculation
*/

IF OBJECT_ID('dbo.CC_TARIFF_ITEMS', 'U') IS NOT NULL DROP TABLE dbo.CC_TARIFF_ITEMS;
GO

CREATE TABLE dbo.CC_TARIFF_ITEMS (
    TI_Id INT IDENTITY(1,1) NOT NULL,
    HS6_COD NVARCHAR(20) NOT NULL,
    TAR_PR1 NVARCHAR(10) NULL,
    TAR_DSC NVARCHAR(500) NULL,
    UOM_COD1 NVARCHAR(10) NULL,
    UOM_COD2 NVARCHAR(10) NULL,
    TAR_T01 DECIMAL(18, 4) DEFAULT 0,
    TAR_T02 DECIMAL(18, 4) DEFAULT 0,
    TAR_T04 DECIMAL(18, 4) DEFAULT 0,
    TAR_T05 DECIMAL(18, 4) DEFAULT 0,
    TAR_T06 DECIMAL(18, 4) DEFAULT 0,
    TAR_T07 DECIMAL(18, 4) DEFAULT 0,
    TAR_T08 DECIMAL(18, 4) DEFAULT 0,
    TAR_T09 DECIMAL(18, 4) DEFAULT 0,
    TAR_T10 DECIMAL(18, 4) DEFAULT 0,
    TAR_T12 DECIMAL(18, 4) DEFAULT 0,
    IS_Active BIT DEFAULT 1,
    Created_At DATETIME DEFAULT GETDATE(),
    CONSTRAINT PK_CC_TARIFF_ITEMS PRIMARY KEY (TI_Id)
);
GO

-- Índice para búsquedas por código arancelario
CREATE INDEX IX_CC_TARIFF_ITEMS_HS6_COD ON dbo.CC_TARIFF_ITEMS (HS6_COD);
GO
select * from [dbo].[CC_GOODS_CLASSIFICATION]
select * from CC_GOODS_CLASSIFICATION
WHERE GC_ITEM_CODE='101482'
