IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CC_VENDOR_CIF')
BEGIN
    CREATE TABLE dbo.CC_VENDOR_CIF (
        VCIF_Vendor NVARCHAR(20) NOT NULL CONSTRAINT PK_CC_VENDOR_CIF PRIMARY KEY
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CC_VENDOR_FREIGHT_WEIGHT')
BEGIN
    CREATE TABLE dbo.CC_VENDOR_FREIGHT_WEIGHT (
        VFW_Vendor NVARCHAR(20) NOT NULL CONSTRAINT PK_CC_VENDOR_FREIGHT_WEIGHT PRIMARY KEY
    );
END
GO

INSERT INTO CC_VENDOR_FREIGHT_WEIGHT
VALUES ('SPB')
DROP TABLE CC_VENDOR_FREIGHT_WEIGHT;