-- Script DEFINITIVO para limpiar todas las cotizaciones y aplicar la restricción global

-- LCL Charges (Nombres corregidos)
DELETE FROM FF_QUOTE_LCL_PORT_TYPE_DET;
DELETE FROM FF_QUOTE_LCL_PORT_TYPE;
DELETE FROM FF_QUOTE_LCL_PORT;

-- Inland Charges
DELETE FROM FF_QUOTE_INLAND_REGION_TYPE_DETAIL;
DELETE FROM FF_QUOTE_INLAND_REGION_TYPE;
DELETE FROM FF_QUOTE_INLAND_REGION;

DELETE FROM FF_QUOTE_INL_REGION_TYPE_DET;
DELETE FROM FF_QUOTE_INL_REGION_TYPE;
DELETE FROM FF_QUOTE_INL_REGION;

-- Port Additional Charges
DELETE FROM FF_QUOTE_INL_PORT_ADD;

-- Ocean Charges
DELETE FROM FF_QUOTE_OCEAN_CHARGE;
DELETE FROM FF_QUOTE_INL_REGION_TYPE;
DELETE FROM FF_QUOTE_OCEAN_PORT;

-- Header (La tabla principal)
DELETE FROM FF_QUOTE_HEADER;
GO

-- Eliminar la restricción antigua (si aún existe)
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'UQ_FF_QUOTE_HEADER_Num_Type' AND type = 'UQ')
BEGIN
    ALTER TABLE FF_QUOTE_HEADER DROP CONSTRAINT UQ_FF_QUOTE_HEADER_Num_Type;
END
GO

-- Crear la nueva restricción única global
ALTER TABLE FF_QUOTE_HEADER ADD CONSTRAINT UQ_FF_QUOTE_HEADER_Num_Global UNIQUE (FQH_QUOTE_NUMBER);
GO
