-- Add CCPD_CLiter column (centiliters = UM * 100 = ml / 10)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'COST_CALC_PO_DET_FIN' AND COLUMN_NAME = 'CCPD_CLiter'
)
BEGIN
    ALTER TABLE COST_CALC_PO_DET_FIN ADD CCPD_CLiter DECIMAL(18,4) NULL;
END
