-- COST_CALC_PO_DET_FIN: Add CCPD_Ml (ml per bottle) and CCPD_Tot_Liters (supplementary liters)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'COST_CALC_PO_DET_FIN' AND COLUMN_NAME = 'CCPD_Ml'
)
BEGIN
    ALTER TABLE COST_CALC_PO_DET_FIN ADD CCPD_Ml INT NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'COST_CALC_PO_DET_FIN' AND COLUMN_NAME = 'CCPD_Tot_Liters'
)
BEGIN
    ALTER TABLE COST_CALC_PO_DET_FIN ADD CCPD_Tot_Liters DECIMAL(18,4) NULL;
END

-- CC_CALC_PO_DET_BENAMING_SUM: Add CCPDS_OrdQty and CCPDS_Cost_Org
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CC_CALC_PO_DET_BENAMING_SUM' AND COLUMN_NAME = 'CCPDS_OrdQty'
)
BEGIN
    ALTER TABLE CC_CALC_PO_DET_BENAMING_SUM ADD CCPDS_OrdQty DECIMAL(18,4) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CC_CALC_PO_DET_BENAMING_SUM' AND COLUMN_NAME = 'CCPDS_Cost_Org'
)
BEGIN
    ALTER TABLE CC_CALC_PO_DET_BENAMING_SUM ADD CCPDS_Cost_Org DECIMAL(18,4) NULL;
END
