USE LicoresMaduoDB;
GO

-- Add display columns to CC_PRICE_CONFIRMATION for Level 2 grid
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'CC_PRICE_CONFIRMATION' AND COLUMN_NAME = 'CCPC_Description')
BEGIN
    ALTER TABLE dbo.CC_PRICE_CONFIRMATION ADD CCPC_Description   NVARCHAR(200)  NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'CC_PRICE_CONFIRMATION' AND COLUMN_NAME = 'CCPC_OrdQty')
BEGIN
    ALTER TABLE dbo.CC_PRICE_CONFIRMATION ADD CCPC_OrdQty        DECIMAL(18,4)  NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'CC_PRICE_CONFIRMATION' AND COLUMN_NAME = 'CCPC_FobFc')
BEGIN
    ALTER TABLE dbo.CC_PRICE_CONFIRMATION ADD CCPC_FobFc         DECIMAL(18,4)  NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'CC_PRICE_CONFIRMATION' AND COLUMN_NAME = 'CCPC_AllowedMargin')
BEGIN
    ALTER TABLE dbo.CC_PRICE_CONFIRMATION ADD CCPC_AllowedMargin DECIMAL(18,4)  NULL;
END
GO

-- Verify
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CC_PRICE_CONFIRMATION'
  AND COLUMN_NAME IN ('CCPC_Description','CCPC_OrdQty','CCPC_FobFc','CCPC_AllowedMargin')
ORDER BY COLUMN_NAME;
GO
