-- ============================================================
-- Licores Maduro - Web-Managed Business Tables (66 tables)
-- Script: 03_WebManagedTables.sql
-- ============================================================

USE LicoresMaduoDB;
GO

-- ============================================================
-- MODULE 1: TRACKING (1 table)
-- ============================================================

IF OBJECT_ID('dbo.ORDER_STATUS', 'U') IS NOT NULL DROP TABLE dbo.ORDER_STATUS;
GO
CREATE TABLE dbo.ORDER_STATUS (
    OS_Id          INT             NOT NULL IDENTITY(1,1),
    OS_Code        NVARCHAR(10)    NOT NULL,
    OS_DESCRIPTION NVARCHAR(100)   NOT NULL,
    IsActive       BIT             NOT NULL DEFAULT 1,
    CreatedAt      DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ORDER_STATUS PRIMARY KEY CLUSTERED (OS_Id),
    CONSTRAINT UQ_ORDER_STATUS_Code UNIQUE (OS_Code),
    CONSTRAINT UQ_ORDER_STATUS_Desc UNIQUE (OS_DESCRIPTION)
);
GO
CREATE INDEX IX_ORDER_STATUS_IsActive ON dbo.ORDER_STATUS (IsActive);
GO

-- ============================================================
-- MODULE 2: FREIGHT FORWARDER (17 tables)
-- ============================================================

IF OBJECT_ID('dbo.CURRENCIES', 'U') IS NOT NULL DROP TABLE dbo.CURRENCIES;
GO
CREATE TABLE dbo.CURRENCIES (
    CUR_Id                 INT             NOT NULL IDENTITY(1,1),
    CUR_CODE               NVARCHAR(3)     NOT NULL,
    CUR_DESCRIPTION        NVARCHAR(30)    NOT NULL,
    CUR_BNK_PURCHASE_RATE  FLOAT           NULL,
    CUR_CUSTOMS_RATE       FLOAT           NULL,
    IsActive               BIT             NOT NULL DEFAULT 1,
    CreatedAt              DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CURRENCIES PRIMARY KEY CLUSTERED (CUR_Id),
    CONSTRAINT UQ_CURRENCIES_Code UNIQUE (CUR_CODE)
);
GO
CREATE INDEX IX_CURRENCIES_IsActive ON dbo.CURRENCIES (IsActive);
GO

IF OBJECT_ID('dbo.LOADTYPES', 'U') IS NOT NULL DROP TABLE dbo.LOADTYPES;
GO
CREATE TABLE dbo.LOADTYPES (
    LT_Id           INT             NOT NULL IDENTITY(1,1),
    LT_CODE         NVARCHAR(6)     NOT NULL,
    LT_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_LOADTYPES PRIMARY KEY CLUSTERED (LT_Id),
    CONSTRAINT UQ_LOADTYPES_Code UNIQUE (LT_CODE)
);
GO

IF OBJECT_ID('dbo.PORT_OF_LOADING', 'U') IS NOT NULL DROP TABLE dbo.PORT_OF_LOADING;
GO
CREATE TABLE dbo.PORT_OF_LOADING (
    PL_Id      INT             NOT NULL IDENTITY(1,1),
    PL_CODE    NVARCHAR(10)    NOT NULL,
    PL_NAME    NVARCHAR(30)    NOT NULL,
    PL_COUNTRY NVARCHAR(3)     NOT NULL,
    IsActive   BIT             NOT NULL DEFAULT 1,
    CreatedAt  DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_PORT_OF_LOADING PRIMARY KEY CLUSTERED (PL_Id),
    CONSTRAINT UQ_PORT_OF_LOADING_Code UNIQUE (PL_CODE)
);
GO
CREATE INDEX IX_PORT_OF_LOADING_Country ON dbo.PORT_OF_LOADING (PL_COUNTRY);
GO

IF OBJECT_ID('dbo.SHIPPING_LINES', 'U') IS NOT NULL DROP TABLE dbo.SHIPPING_LINES;
GO
CREATE TABLE dbo.SHIPPING_LINES (
    SL_Id      INT             NOT NULL IDENTITY(1,1),
    SL_CODE    NVARCHAR(10)    NOT NULL,
    SL_NAME    NVARCHAR(30)    NOT NULL,
    IsActive   BIT             NOT NULL DEFAULT 1,
    CreatedAt  DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_SHIPPING_LINES PRIMARY KEY CLUSTERED (SL_Id),
    CONSTRAINT UQ_SHIPPING_LINES_Code UNIQUE (SL_CODE)
);
GO

IF OBJECT_ID('dbo.SHIPPING_AGENT', 'U') IS NOT NULL DROP TABLE dbo.SHIPPING_AGENT;
GO
CREATE TABLE dbo.SHIPPING_AGENT (
    SA_Id      INT             NOT NULL IDENTITY(1,1),
    SA_CODE    NVARCHAR(10)    NOT NULL,
    SA_NAME    NVARCHAR(30)    NOT NULL,
    IsActive   BIT             NOT NULL DEFAULT 1,
    CreatedAt  DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_SHIPPING_AGENT PRIMARY KEY CLUSTERED (SA_Id),
    CONSTRAINT UQ_SHIPPING_AGENT_Code UNIQUE (SA_CODE)
);
GO

IF OBJECT_ID('dbo.ROUTES', 'U') IS NOT NULL DROP TABLE dbo.ROUTES;
GO
CREATE TABLE dbo.ROUTES (
    ROU_Id          INT             NOT NULL IDENTITY(1,1),
    ROU_CODE        NVARCHAR(15)    NOT NULL,
    ROU_DESCRIPTION NVARCHAR(30)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ROUTES PRIMARY KEY CLUSTERED (ROU_Id),
    CONSTRAINT UQ_ROUTES_Code UNIQUE (ROU_CODE)
);
GO

IF OBJECT_ID('dbo.CONTAINER_SPECS', 'U') IS NOT NULL DROP TABLE dbo.CONTAINER_SPECS;
GO
CREATE TABLE dbo.CONTAINER_SPECS (
    CS_Id           INT             NOT NULL IDENTITY(1,1),
    CS_CODE         NVARCHAR(6)     NOT NULL,
    CS_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CONTAINER_SPECS PRIMARY KEY CLUSTERED (CS_Id),
    CONSTRAINT UQ_CONTAINER_SPECS_Code UNIQUE (CS_CODE)
);
GO

IF OBJECT_ID('dbo.CONTAINER_TYPES', 'U') IS NOT NULL DROP TABLE dbo.CONTAINER_TYPES;
GO
CREATE TABLE dbo.CONTAINER_TYPES (
    CT_Id               INT             NOT NULL IDENTITY(1,1),
    CT_CODE             NVARCHAR(6)     NOT NULL,
    CT_DESCRIPTION      NVARCHAR(50)    NOT NULL,
    CT_CONTAINER_SPECS  NVARCHAR(6)     NULL,
    CT_Cases            INT             NULL,
    CT_WGHT_Kilogram    INT             NULL,
    IsActive            BIT             NOT NULL DEFAULT 1,
    CreatedAt           DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CONTAINER_TYPES PRIMARY KEY CLUSTERED (CT_Id),
    CONSTRAINT UQ_CONTAINER_TYPES_Code UNIQUE (CT_CODE)
);
GO

IF OBJECT_ID('dbo.ROUTES_BY_SHIPPING_AGENTS', 'U') IS NOT NULL DROP TABLE dbo.ROUTES_BY_SHIPPING_AGENTS;
GO
CREATE TABLE dbo.ROUTES_BY_SHIPPING_AGENTS (
    RSA_Id            INT             NOT NULL IDENTITY(1,1),
    RSA_PORT          NVARCHAR(10)    NOT NULL,
    RSA_SHIPPING_AGENT NVARCHAR(25)   NOT NULL,
    RSA_ROUTE         NVARCHAR(10)    NOT NULL,
    RSA_DAYS          SMALLINT        NULL,
    IsActive          BIT             NOT NULL DEFAULT 1,
    CreatedAt         DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ROUTES_BY_SHIPPING_AGENTS PRIMARY KEY CLUSTERED (RSA_Id)
);
GO
CREATE INDEX IX_RSA_Port  ON dbo.ROUTES_BY_SHIPPING_AGENTS (RSA_PORT);
CREATE INDEX IX_RSA_Agent ON dbo.ROUTES_BY_SHIPPING_AGENTS (RSA_SHIPPING_AGENT);
GO

IF OBJECT_ID('dbo.OCEAN_FREIGHT_CHARGE_TYPES', 'U') IS NOT NULL DROP TABLE dbo.OCEAN_FREIGHT_CHARGE_TYPES;
GO
CREATE TABLE dbo.OCEAN_FREIGHT_CHARGE_TYPES (
    OFCT_Id          INT             NOT NULL IDENTITY(1,1),
    OFCT_CODE        NVARCHAR(6)     NOT NULL,
    OFCT_DESCRIPTION NVARCHAR(25)    NOT NULL,
    IsActive         BIT             NOT NULL DEFAULT 1,
    CreatedAt        DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_OCEAN_FREIGHT_CHARGE_TYPES PRIMARY KEY CLUSTERED (OFCT_Id),
    CONSTRAINT UQ_OFCT_Code UNIQUE (OFCT_CODE)
);
GO

IF OBJECT_ID('dbo.INLAND_FREIGHT_CHARGE_TYPES', 'U') IS NOT NULL DROP TABLE dbo.INLAND_FREIGHT_CHARGE_TYPES;
GO
CREATE TABLE dbo.INLAND_FREIGHT_CHARGE_TYPES (
    IFCT_Id          INT             NOT NULL IDENTITY(1,1),
    IFCT_CODE        NVARCHAR(6)     NOT NULL,
    IFCT_DESCRIPTION NVARCHAR(25)    NOT NULL,
    IsActive         BIT             NOT NULL DEFAULT 1,
    CreatedAt        DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_INLAND_FREIGHT_CHARGE_TYPES PRIMARY KEY CLUSTERED (IFCT_Id),
    CONSTRAINT UQ_IFCT_Code UNIQUE (IFCT_CODE)
);
GO

IF OBJECT_ID('dbo.LCL_CHARGE_TYPES', 'U') IS NOT NULL DROP TABLE dbo.LCL_CHARGE_TYPES;
GO
CREATE TABLE dbo.LCL_CHARGE_TYPES (
    LCT_Id          INT             NOT NULL IDENTITY(1,1),
    LCT_CODE        NVARCHAR(6)     NOT NULL,
    LCT_DESCRIPTION NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_LCL_CHARGE_TYPES PRIMARY KEY CLUSTERED (LCT_Id),
    CONSTRAINT UQ_LCT_Code UNIQUE (LCT_CODE)
);
GO

IF OBJECT_ID('dbo.PRICE_TYPE', 'U') IS NOT NULL DROP TABLE dbo.PRICE_TYPE;
GO
CREATE TABLE dbo.PRICE_TYPE (
    PT_Id           INT             NOT NULL IDENTITY(1,1),
    PT_CODE         NVARCHAR(6)     NOT NULL,
    PT_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_PRICE_TYPE PRIMARY KEY CLUSTERED (PT_Id),
    CONSTRAINT UQ_PRICE_TYPE_Code UNIQUE (PT_CODE)
);
GO

IF OBJECT_ID('dbo.AMOUNT_TYPE', 'U') IS NOT NULL DROP TABLE dbo.AMOUNT_TYPE;
GO
CREATE TABLE dbo.AMOUNT_TYPE (
    AT_Id           INT             NOT NULL IDENTITY(1,1),
    AT_CODE         NVARCHAR(1)     NOT NULL,
    AT_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_AMOUNT_TYPE PRIMARY KEY CLUSTERED (AT_Id),
    CONSTRAINT UQ_AMOUNT_TYPE_Code UNIQUE (AT_CODE)
);
GO

IF OBJECT_ID('dbo.CHARGE_ACTION', 'U') IS NOT NULL DROP TABLE dbo.CHARGE_ACTION;
GO
CREATE TABLE dbo.CHARGE_ACTION (
    CA_Id           INT             NOT NULL IDENTITY(1,1),
    CA_CODE         NVARCHAR(6)     NOT NULL,
    CA_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CHARGE_ACTION PRIMARY KEY CLUSTERED (CA_Id),
    CONSTRAINT UQ_CHARGE_ACTION_Code UNIQUE (CA_CODE)
);
GO

IF OBJECT_ID('dbo.CHARGE_OVER', 'U') IS NOT NULL DROP TABLE dbo.CHARGE_OVER;
GO
CREATE TABLE dbo.CHARGE_OVER (
    CO_Id           INT             NOT NULL IDENTITY(1,1),
    CO_CODE         NVARCHAR(6)     NOT NULL,
    CO_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CHARGE_OVER PRIMARY KEY CLUSTERED (CO_Id),
    CONSTRAINT UQ_CHARGE_OVER_Code UNIQUE (CO_CODE)
);
GO

IF OBJECT_ID('dbo.CHARGE_PER', 'U') IS NOT NULL DROP TABLE dbo.CHARGE_PER;
GO
CREATE TABLE dbo.CHARGE_PER (
    CP_Id           INT             NOT NULL IDENTITY(1,1),
    CP_CODE         NVARCHAR(6)     NOT NULL,
    CP_DESCRIPTION  NVARCHAR(25)    NOT NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CHARGE_PER PRIMARY KEY CLUSTERED (CP_Id),
    CONSTRAINT UQ_CHARGE_PER_Code UNIQUE (CP_CODE)
);
GO

-- ============================================================
-- MODULE 6: ACTIVITY REQUEST (38 tables)
-- ============================================================

IF OBJECT_ID('dbo.ACTIVITY_TYPE', 'U') IS NOT NULL DROP TABLE dbo.ACTIVITY_TYPE;
GO
CREATE TABLE dbo.ACTIVITY_TYPE (
    AT_Id            INT             NOT NULL IDENTITY(1,1),
    Code             NVARCHAR(6)     NOT NULL,
    Description      NVARCHAR(30)    NOT NULL,
    Activity_Related BIT             NOT NULL DEFAULT 0,
    IsActive         BIT             NOT NULL DEFAULT 1,
    CreatedAt        DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY CLUSTERED (AT_Id),
    CONSTRAINT UQ_ACTIVITY_TYPE_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.BUDGET_ACTIVITIES', 'U') IS NOT NULL DROP TABLE dbo.BUDGET_ACTIVITIES;
GO
CREATE TABLE dbo.BUDGET_ACTIVITIES (
    BA_Id          INT             NOT NULL IDENTITY(1,1),
    Code           NVARCHAR(6)     NOT NULL,
    Description    NVARCHAR(50)    NOT NULL,
    BillingDescr   NVARCHAR(30)    NULL,
    DisplaySeq     SMALLINT        NULL,
    IsActive       BIT             NOT NULL DEFAULT 1,
    CreatedAt      DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_BUDGET_ACTIVITIES PRIMARY KEY CLUSTERED (BA_Id),
    CONSTRAINT UQ_BUDGET_ACTIVITIES_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.CAT_ADD_SPECS', 'U') IS NOT NULL DROP TABLE dbo.CAT_ADD_SPECS;
GO
CREATE TABLE dbo.CAT_ADD_SPECS (
    CAS_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_ADD_SPECS PRIMARY KEY CLUSTERED (CAS_Id)
);
GO

IF OBJECT_ID('dbo.CAT_APPAREL_TYPE', 'U') IS NOT NULL DROP TABLE dbo.CAT_APPAREL_TYPE;
GO
CREATE TABLE dbo.CAT_APPAREL_TYPE (
    CAT_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_APPAREL_TYPE PRIMARY KEY CLUSTERED (CAT_Id)
);
GO

IF OBJECT_ID('dbo.CAT_BAG_SPECS', 'U') IS NOT NULL DROP TABLE dbo.CAT_BAG_SPECS;
GO
CREATE TABLE dbo.CAT_BAG_SPECS (
    CBS_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_BAG_SPECS PRIMARY KEY CLUSTERED (CBS_Id)
);
GO

IF OBJECT_ID('dbo.CAT_BOTTLES', 'U') IS NOT NULL DROP TABLE dbo.CAT_BOTTLES;
GO
CREATE TABLE dbo.CAT_BOTTLES (
    CB_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_BOTTLES PRIMARY KEY CLUSTERED (CB_Id)
);
GO

IF OBJECT_ID('dbo.CAT_BRAND_SPECIFIC', 'U') IS NOT NULL DROP TABLE dbo.CAT_BRAND_SPECIFIC;
GO
CREATE TABLE dbo.CAT_BRAND_SPECIFIC (
    CBR_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_BRAND_SPECIFIC PRIMARY KEY CLUSTERED (CBR_Id)
);
GO

IF OBJECT_ID('dbo.CAT_CLOTHING_TYPE', 'U') IS NOT NULL DROP TABLE dbo.CAT_CLOTHING_TYPE;
GO
CREATE TABLE dbo.CAT_CLOTHING_TYPE (
    CCT_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_CLOTHING_TYPE PRIMARY KEY CLUSTERED (CCT_Id)
);
GO

IF OBJECT_ID('dbo.CAT_COLORS', 'U') IS NOT NULL DROP TABLE dbo.CAT_COLORS;
GO
CREATE TABLE dbo.CAT_COLORS (
    CC_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_COLORS PRIMARY KEY CLUSTERED (CC_Id)
);
GO

IF OBJECT_ID('dbo.CAT_CONTENT', 'U') IS NOT NULL DROP TABLE dbo.CAT_CONTENT;
GO
CREATE TABLE dbo.CAT_CONTENT (
    CCO_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_CONTENT PRIMARY KEY CLUSTERED (CCO_Id)
);
GO

IF OBJECT_ID('dbo.CAT_COOLER_CAPACITY', 'U') IS NOT NULL DROP TABLE dbo.CAT_COOLER_CAPACITY;
GO
CREATE TABLE dbo.CAT_COOLER_CAPACITY (
    CCC_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_COOLER_CAPACITY PRIMARY KEY CLUSTERED (CCC_Id)
);
GO

IF OBJECT_ID('dbo.CAT_COOLER_MODEL', 'U') IS NOT NULL DROP TABLE dbo.CAT_COOLER_MODEL;
GO
CREATE TABLE dbo.CAT_COOLER_MODEL (
    CCM_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_COOLER_MODEL PRIMARY KEY CLUSTERED (CCM_Id)
);
GO

IF OBJECT_ID('dbo.CAT_COOLER_TYPE', 'U') IS NOT NULL DROP TABLE dbo.CAT_COOLER_TYPE;
GO
CREATE TABLE dbo.CAT_COOLER_TYPE (
    CCTY_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Prefix NVARCHAR(1)     NULL,
    CAT_Sel    NVARCHAR(25)    NOT NULL,
    IsActive   BIT             NOT NULL DEFAULT 1,
    CreatedAt  DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_COOLER_TYPE PRIMARY KEY CLUSTERED (CCTY_Id)
);
GO

IF OBJECT_ID('dbo.CAT_FILE_NAMES', 'U') IS NOT NULL DROP TABLE dbo.CAT_FILE_NAMES;
GO
CREATE TABLE dbo.CAT_FILE_NAMES (
    CFN_Id       INT             NOT NULL IDENTITY(1,1),
    File_Names   NVARCHAR(100)   NOT NULL,
    Display_Text NVARCHAR(100)   NULL,
    IsActive     BIT             NOT NULL DEFAULT 1,
    CreatedAt    DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_FILE_NAMES PRIMARY KEY CLUSTERED (CFN_Id)
);
GO

IF OBJECT_ID('dbo.CAT_GENDER', 'U') IS NOT NULL DROP TABLE dbo.CAT_GENDER;
GO
CREATE TABLE dbo.CAT_GENDER (
    CG_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_GENDER PRIMARY KEY CLUSTERED (CG_Id)
);
GO

IF OBJECT_ID('dbo.CAT_GLASS_SERVING', 'U') IS NOT NULL DROP TABLE dbo.CAT_GLASS_SERVING;
GO
CREATE TABLE dbo.CAT_GLASS_SERVING (
    CGS_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_GLASS_SERVING PRIMARY KEY CLUSTERED (CGS_Id)
);
GO

IF OBJECT_ID('dbo.CAT_INSURRANCE', 'U') IS NOT NULL DROP TABLE dbo.CAT_INSURRANCE;
GO
CREATE TABLE dbo.CAT_INSURRANCE (
    CI_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_INSURRANCE PRIMARY KEY CLUSTERED (CI_Id)
);
GO

IF OBJECT_ID('dbo.CAT_LED', 'U') IS NOT NULL DROP TABLE dbo.CAT_LED;
GO
CREATE TABLE dbo.CAT_LED (
    CL_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_LED PRIMARY KEY CLUSTERED (CL_Id)
);
GO

IF OBJECT_ID('dbo.CAT_MAINT_MONTHS', 'U') IS NOT NULL DROP TABLE dbo.CAT_MAINT_MONTHS;
GO
CREATE TABLE dbo.CAT_MAINT_MONTHS (
    CMM_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_MAINT_MONTHS PRIMARY KEY CLUSTERED (CMM_Id)
);
GO

IF OBJECT_ID('dbo.CAT_MATERIALS', 'U') IS NOT NULL DROP TABLE dbo.CAT_MATERIALS;
GO
CREATE TABLE dbo.CAT_MATERIALS (
    CM_Id     INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_MATERIALS PRIMARY KEY CLUSTERED (CM_Id)
);
GO

IF OBJECT_ID('dbo.CAT_SHAPES', 'U') IS NOT NULL DROP TABLE dbo.CAT_SHAPES;
GO
CREATE TABLE dbo.CAT_SHAPES (
    CS2_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_SHAPES PRIMARY KEY CLUSTERED (CS2_Id)
);
GO

IF OBJECT_ID('dbo.CAT_SIZES', 'U') IS NOT NULL DROP TABLE dbo.CAT_SIZES;
GO
CREATE TABLE dbo.CAT_SIZES (
    CSZ_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_SIZES PRIMARY KEY CLUSTERED (CSZ_Id)
);
GO

IF OBJECT_ID('dbo.CAT_VAP_TYPE', 'U') IS NOT NULL DROP TABLE dbo.CAT_VAP_TYPE;
GO
CREATE TABLE dbo.CAT_VAP_TYPE (
    CVT_Id    INT             NOT NULL IDENTITY(1,1),
    CAT_Sel   NVARCHAR(25)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CAT_VAP_TYPE PRIMARY KEY CLUSTERED (CVT_Id)
);
GO

IF OBJECT_ID('dbo.CUSTOMER_NON_CLIENT', 'U') IS NOT NULL DROP TABLE dbo.CUSTOMER_NON_CLIENT;
GO
CREATE TABLE dbo.CUSTOMER_NON_CLIENT (
    CNC_Id    INT             NOT NULL IDENTITY(1,1),
    Code      NVARCHAR(20)    NOT NULL,
    Name      NVARCHAR(100)   NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CUSTOMER_NON_CLIENT PRIMARY KEY CLUSTERED (CNC_Id),
    CONSTRAINT UQ_CUSTOMER_NON_CLIENT_Code UNIQUE (Code)
);
GO
CREATE INDEX IX_CUSTOMER_NON_CLIENT_Name ON dbo.CUSTOMER_NON_CLIENT (Name);
GO

IF OBJECT_ID('dbo.CUSTOMER_SALES_GROUP', 'U') IS NOT NULL DROP TABLE dbo.CUSTOMER_SALES_GROUP;
GO
CREATE TABLE dbo.CUSTOMER_SALES_GROUP (
    CSG_Id    INT             NOT NULL IDENTITY(1,1),
    Code      NVARCHAR(20)    NOT NULL,
    Name      NVARCHAR(100)   NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CUSTOMER_SALES_GROUP PRIMARY KEY CLUSTERED (CSG_Id),
    CONSTRAINT UQ_CUSTOMER_SALES_GROUP_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.CUSTOMER_SEGMENT_INFO', 'U') IS NOT NULL DROP TABLE dbo.CUSTOMER_SEGMENT_INFO;
GO
CREATE TABLE dbo.CUSTOMER_SEGMENT_INFO (
    CSI_Id      INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(20)    NOT NULL,
    Description NVARCHAR(100)   NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CUSTOMER_SEGMENT_INFO PRIMARY KEY CLUSTERED (CSI_Id),
    CONSTRAINT UQ_CUSTOMER_SEGMENT_INFO_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.CUSTOMER_TARGET_GROUP', 'U') IS NOT NULL DROP TABLE dbo.CUSTOMER_TARGET_GROUP;
GO
CREATE TABLE dbo.CUSTOMER_TARGET_GROUP (
    CTG_Id      INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(20)    NOT NULL,
    Description NVARCHAR(100)   NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_CUSTOMER_TARGET_GROUP PRIMARY KEY CLUSTERED (CTG_Id),
    CONSTRAINT UQ_CUSTOMER_TARGET_GROUP_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.DENIAL_REASONS', 'U') IS NOT NULL DROP TABLE dbo.DENIAL_REASONS;
GO
CREATE TABLE dbo.DENIAL_REASONS (
    DR_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(100)   NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_DENIAL_REASONS PRIMARY KEY CLUSTERED (DR_Id),
    CONSTRAINT UQ_DENIAL_REASONS_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.ENTERTAINMENT_TYPE', 'U') IS NOT NULL DROP TABLE dbo.ENTERTAINMENT_TYPE;
GO
CREATE TABLE dbo.ENTERTAINMENT_TYPE (
    ET_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_ENTERTAINMENT_TYPE PRIMARY KEY CLUSTERED (ET_Id),
    CONSTRAINT UQ_ENTERTAINMENT_TYPE_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.FACILITATORS_INFO', 'U') IS NOT NULL DROP TABLE dbo.FACILITATORS_INFO;
GO
CREATE TABLE dbo.FACILITATORS_INFO (
    FI_Id     INT             NOT NULL IDENTITY(1,1),
    Code      NVARCHAR(20)    NOT NULL,
    Name      NVARCHAR(100)   NOT NULL,
    Email     NVARCHAR(100)   NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_FACILITATORS_INFO PRIMARY KEY CLUSTERED (FI_Id),
    CONSTRAINT UQ_FACILITATORS_INFO_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.FISCAL_YEARS', 'U') IS NOT NULL DROP TABLE dbo.FISCAL_YEARS;
GO
CREATE TABLE dbo.FISCAL_YEARS (
    FY_Id        INT             NOT NULL IDENTITY(1,1),
    FY_Year      INT             NOT NULL,
    FY_StartDate DATE            NOT NULL,
    FY_EndDate   DATE            NOT NULL,
    IsActive     BIT             NOT NULL DEFAULT 1,
    CreatedAt    DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_FISCAL_YEARS PRIMARY KEY CLUSTERED (FY_Id),
    CONSTRAINT UQ_FISCAL_YEARS_Year UNIQUE (FY_Year)
);
GO

IF OBJECT_ID('dbo.LICORES_GROUP', 'U') IS NOT NULL DROP TABLE dbo.LICORES_GROUP;
GO
CREATE TABLE dbo.LICORES_GROUP (
    LG_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(10)    NOT NULL,
    Description NVARCHAR(100)   NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_LICORES_GROUP PRIMARY KEY CLUSTERED (LG_Id),
    CONSTRAINT UQ_LICORES_GROUP_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.LOCATION_INFO', 'U') IS NOT NULL DROP TABLE dbo.LOCATION_INFO;
GO
CREATE TABLE dbo.LOCATION_INFO (
    LI_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(20)    NOT NULL,
    Description NVARCHAR(100)   NOT NULL,
    Address     NVARCHAR(200)   NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_LOCATION_INFO PRIMARY KEY CLUSTERED (LI_Id),
    CONSTRAINT UQ_LOCATION_INFO_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.POS_CATEGORY', 'U') IS NOT NULL DROP TABLE dbo.POS_CATEGORY;
GO
CREATE TABLE dbo.POS_CATEGORY (
    PC_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(10)    NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_POS_CATEGORY PRIMARY KEY CLUSTERED (PC_Id),
    CONSTRAINT UQ_POS_CATEGORY_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.POS_LEND_GIVE', 'U') IS NOT NULL DROP TABLE dbo.POS_LEND_GIVE;
GO
CREATE TABLE dbo.POS_LEND_GIVE (
    PLG_Id      INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_POS_LEND_GIVE PRIMARY KEY CLUSTERED (PLG_Id),
    CONSTRAINT UQ_POS_LEND_GIVE_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.POS_MATERIALS_STATUS', 'U') IS NOT NULL DROP TABLE dbo.POS_MATERIALS_STATUS;
GO
CREATE TABLE dbo.POS_MATERIALS_STATUS (
    PMS_Id      INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_POS_MATERIALS_STATUS PRIMARY KEY CLUSTERED (PMS_Id),
    CONSTRAINT UQ_POS_MATERIALS_STATUS_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.SPONSORING_TYPE', 'U') IS NOT NULL DROP TABLE dbo.SPONSORING_TYPE;
GO
CREATE TABLE dbo.SPONSORING_TYPE (
    ST_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_SPONSORING_TYPE PRIMARY KEY CLUSTERED (ST_Id),
    CONSTRAINT UQ_SPONSORING_TYPE_Code UNIQUE (Code)
);
GO

IF OBJECT_ID('dbo.STATUS_CODES', 'U') IS NOT NULL DROP TABLE dbo.STATUS_CODES;
GO
CREATE TABLE dbo.STATUS_CODES (
    SC_Id       INT             NOT NULL IDENTITY(1,1),
    Code        NVARCHAR(6)     NOT NULL,
    Description NVARCHAR(50)    NOT NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_STATUS_CODES PRIMARY KEY CLUSTERED (SC_Id),
    CONSTRAINT UQ_STATUS_CODES_Code UNIQUE (Code)
);
GO

-- ============================================================
-- MODULE 7: AANKOOPBON (10 tables)
-- ============================================================

IF OBJECT_ID('dbo.COST_TYPE', 'U') IS NOT NULL DROP TABLE dbo.COST_TYPE;
GO
CREATE TABLE dbo.COST_TYPE (
    CT_Id     INT             NOT NULL IDENTITY(1,1),
    TC_NAME   NVARCHAR(15)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_COST_TYPE PRIMARY KEY CLUSTERED (CT_Id),
    CONSTRAINT UQ_COST_TYPE_Name UNIQUE (TC_NAME)
);
GO

IF OBJECT_ID('dbo.VEHICLE_TYPE', 'U') IS NOT NULL DROP TABLE dbo.VEHICLE_TYPE;
GO
CREATE TABLE dbo.VEHICLE_TYPE (
    VT_Id     INT             NOT NULL IDENTITY(1,1),
    VT_NAME   NVARCHAR(15)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_VEHICLE_TYPE PRIMARY KEY CLUSTERED (VT_Id),
    CONSTRAINT UQ_VEHICLE_TYPE_Name UNIQUE (VT_NAME)
);
GO

IF OBJECT_ID('dbo.DEPARTMENTS', 'U') IS NOT NULL DROP TABLE dbo.DEPARTMENTS;
GO
CREATE TABLE dbo.DEPARTMENTS (
    DP_Id     INT             NOT NULL IDENTITY(1,1),
    DP_NAME   NVARCHAR(15)    NOT NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY CLUSTERED (DP_Id),
    CONSTRAINT UQ_DEPARTMENTS_Name UNIQUE (DP_NAME)
);
GO

IF OBJECT_ID('dbo.EENHEDEN', 'U') IS NOT NULL DROP TABLE dbo.EENHEDEN;
GO
CREATE TABLE dbo.EENHEDEN (
    EE_Id           INT             NOT NULL IDENTITY(1,1),
    UnitCode        NVARCHAR(10)    NOT NULL,
    Omschrijving    NVARCHAR(50)    NOT NULL,
    OmrekenFaktor   FLOAT           NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_EENHEDEN PRIMARY KEY CLUSTERED (EE_Id),
    CONSTRAINT UQ_EENHEDEN_Code UNIQUE (UnitCode)
);
GO

IF OBJECT_ID('dbo.RECEIVERS', 'U') IS NOT NULL DROP TABLE dbo.RECEIVERS;
GO
CREATE TABLE dbo.RECEIVERS (
    REC_Id      INT             NOT NULL IDENTITY(1,1),
    REC_NAME    NVARCHAR(30)    NOT NULL,
    REC_ID_DOC  NVARCHAR(15)    NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_RECEIVERS PRIMARY KEY CLUSTERED (REC_Id)
);
GO
CREATE INDEX IX_RECEIVERS_Name ON dbo.RECEIVERS (REC_NAME);
GO

IF OBJECT_ID('dbo.REQUESTORS', 'U') IS NOT NULL DROP TABLE dbo.REQUESTORS;
GO
CREATE TABLE dbo.REQUESTORS (
    REQ_Id    INT             NOT NULL IDENTITY(1,1),
    REQ_NAME  NVARCHAR(15)    NOT NULL,
    REQ_EMAIL NVARCHAR(50)    NULL,
    IsActive  BIT             NOT NULL DEFAULT 1,
    CreatedAt DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_REQUESTORS PRIMARY KEY CLUSTERED (REQ_Id)
);
GO

IF OBJECT_ID('dbo.REQUESTORS_VENDOR', 'U') IS NOT NULL DROP TABLE dbo.REQUESTORS_VENDOR;
GO
CREATE TABLE dbo.REQUESTORS_VENDOR (
    RV_Id         INT             NOT NULL IDENTITY(1,1),
    RS_REQUESTOR  NVARCHAR(15)    NOT NULL,
    RS_VENDOR     NVARCHAR(6)     NOT NULL,
    IsActive      BIT             NOT NULL DEFAULT 1,
    CreatedAt     DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_REQUESTORS_VENDOR PRIMARY KEY CLUSTERED (RV_Id)
);
GO
CREATE INDEX IX_REQUESTORS_VENDOR_Requestor ON dbo.REQUESTORS_VENDOR (RS_REQUESTOR);
CREATE INDEX IX_REQUESTORS_VENDOR_Vendor    ON dbo.REQUESTORS_VENDOR (RS_VENDOR);
GO

IF OBJECT_ID('dbo.VEHICLES', 'U') IS NOT NULL DROP TABLE dbo.VEHICLES;
GO
CREATE TABLE dbo.VEHICLES (
    VH_Id       INT             NOT NULL IDENTITY(1,1),
    VH_LICENSE  NVARCHAR(10)    NOT NULL,
    VH_TYPE     NVARCHAR(15)    NULL,
    VH_MODEL    NVARCHAR(15)    NULL,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_VEHICLES PRIMARY KEY CLUSTERED (VH_Id),
    CONSTRAINT UQ_VEHICLES_License UNIQUE (VH_LICENSE)
);
GO

IF OBJECT_ID('dbo.VENDORS', 'U') IS NOT NULL DROP TABLE dbo.VENDORS;
GO
CREATE TABLE dbo.VENDORS (
    VND_Id      INT             NOT NULL IDENTITY(1,1),
    VND_Code    NVARCHAR(6)     NOT NULL,
    VND_Name    NVARCHAR(100)   NOT NULL,
    VND_Address_1 NVARCHAR(100) NULL,
    VND_Phone_1 NVARCHAR(25)    NULL,
    VND_Email   NVARCHAR(50)    NULL,
    VND_Contact NVARCHAR(100)   NULL,
    VND_CURR    NVARCHAR(3)     NULL,
    VND_CRIB    NVARCHAR(15)    NULL,
    VND_KVK     NVARCHAR(15)    NULL,
    VND_CASH    BIT             NOT NULL DEFAULT 0,
    IsActive    BIT             NOT NULL DEFAULT 1,
    CreatedAt   DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_VENDORS PRIMARY KEY CLUSTERED (VND_Id),
    CONSTRAINT UQ_VENDORS_Code UNIQUE (VND_Code)
);
GO
CREATE INDEX IX_VENDORS_Name     ON dbo.VENDORS (VND_Name);
CREATE INDEX IX_VENDORS_IsActive ON dbo.VENDORS (IsActive);
GO

IF OBJECT_ID('dbo.AB_PRODUCTS', 'U') IS NOT NULL DROP TABLE dbo.AB_PRODUCTS;
GO
CREATE TABLE dbo.AB_PRODUCTS (
    ABP_Id       INT             NOT NULL IDENTITY(1,1),
    ItemKode     NVARCHAR(20)    NOT NULL,
    Omschrijving NVARCHAR(100)   NOT NULL,
    VendorCode   NVARCHAR(6)     NULL,
    Cost_Type    NVARCHAR(15)    NULL,
    Eenheid      NVARCHAR(10)    NULL,
    UnitQuantity FLOAT           NULL,
    IsActive     BIT             NOT NULL DEFAULT 1,
    CreatedAt    DATETIME2       NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_AB_PRODUCTS PRIMARY KEY CLUSTERED (ABP_Id),
    CONSTRAINT UQ_AB_PRODUCTS_ItemKode UNIQUE (ItemKode)
);
GO
CREATE INDEX IX_AB_PRODUCTS_VendorCode  ON dbo.AB_PRODUCTS (VendorCode);
CREATE INDEX IX_AB_PRODUCTS_Omschrijving ON dbo.AB_PRODUCTS (Omschrijving);
GO

PRINT 'All 66 web-managed tables created successfully.';
GO
