-- ============================================================
-- Licores Maduro - Freight Forwarder Main Entity & Quote Tables
-- Script: 06_FreightForwarderQuoteTables.sql
-- Run on: LicoresMaduoDB
-- ============================================================

USE LicoresMaduoDB;
GO

-- ============================================================
-- Drop existing tables (in dependency order)
-- ============================================================
IF OBJECT_ID('dbo.FF_INLAND_ADDITIONAL_CHARGES',         'U') IS NOT NULL DROP TABLE dbo.FF_INLAND_ADDITIONAL_CHARGES;
IF OBJECT_ID('dbo.FF_LCL_PORT_TYPE_DET',                'U') IS NOT NULL DROP TABLE dbo.FF_LCL_PORT_TYPE_DET;
IF OBJECT_ID('dbo.FF_LCL_PORT_TYPE',                    'U') IS NOT NULL DROP TABLE dbo.FF_LCL_PORT_TYPE;
IF OBJECT_ID('dbo.FF_LCL_PORT',                         'U') IS NOT NULL DROP TABLE dbo.FF_LCL_PORT;
IF OBJECT_ID('dbo.FF_LCL_HEADER',                       'U') IS NOT NULL DROP TABLE dbo.FF_LCL_HEADER;
IF OBJECT_ID('dbo.FF_INLAND_FREIGHT_REGION_TYPE_DET',   'U') IS NOT NULL DROP TABLE dbo.FF_INLAND_FREIGHT_REGION_TYPE_DET;
IF OBJECT_ID('dbo.FF_INLAND_FREIGHT_REGION_TYPE',       'U') IS NOT NULL DROP TABLE dbo.FF_INLAND_FREIGHT_REGION_TYPE;
IF OBJECT_ID('dbo.FF_INLAND_FREIGHT_REGION',            'U') IS NOT NULL DROP TABLE dbo.FF_INLAND_FREIGHT_REGION;
IF OBJECT_ID('dbo.FF_INLAND_FREIGHT_HEADER',            'U') IS NOT NULL DROP TABLE dbo.FF_INLAND_FREIGHT_HEADER;
IF OBJECT_ID('dbo.FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES', 'U') IS NOT NULL DROP TABLE dbo.FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES;
IF OBJECT_ID('dbo.FF_OCEAN_FREIGHT_PORT_SLINE',         'U') IS NOT NULL DROP TABLE dbo.FF_OCEAN_FREIGHT_PORT_SLINE;
IF OBJECT_ID('dbo.FF_OCEAN_FREIGHT_PORT',               'U') IS NOT NULL DROP TABLE dbo.FF_OCEAN_FREIGHT_PORT;
IF OBJECT_ID('dbo.FF_OCEAN_FREIGHT_HEADER',             'U') IS NOT NULL DROP TABLE dbo.FF_OCEAN_FREIGHT_HEADER;
IF OBJECT_ID('dbo.FREIGHT_FORWARDERS',                  'U') IS NOT NULL DROP TABLE dbo.FREIGHT_FORWARDERS;
GO

-- ============================================================
-- Table 1: FREIGHT_FORWARDERS
-- Master list of freight forwarding companies.
-- ============================================================
CREATE TABLE dbo.FREIGHT_FORWARDERS (
    FF_Id           INT             NOT NULL IDENTITY(1,1),
    FF_CODE         NVARCHAR(10)    NOT NULL,
    FF_NAME         NVARCHAR(50)    NOT NULL,
    FF_ADDRESS_1    NVARCHAR(100)   NULL,
    FF_ADDRESS_2    NVARCHAR(100)   NULL,
    FF_CITY         NVARCHAR(30)    NULL,
    FF_COUNTRY      NVARCHAR(3)     NULL,
    FF_PHONE_1      NVARCHAR(20)    NULL,
    FF_PHONE_2      NVARCHAR(20)    NULL,
    FF_EMAIL        NVARCHAR(100)   NULL,
    FF_CONTACT      NVARCHAR(50)    NULL,
    FF_CURRENCY     NVARCHAR(3)     NULL,
    IsActive        BIT             NOT NULL DEFAULT 1,
    CreatedAt       DATETIME2       NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_FREIGHT_FORWARDERS        PRIMARY KEY CLUSTERED (FF_Id),
    CONSTRAINT UQ_FREIGHT_FORWARDERS_CODE   UNIQUE (FF_CODE)
);
GO

CREATE INDEX IX_FF_Name ON dbo.FREIGHT_FORWARDERS (FF_NAME);
GO

-- ============================================================
-- OCEAN FREIGHT TABLES (4 levels)
-- ============================================================

-- Table 2: FF_OCEAN_FREIGHT_HEADER
-- One header per quote per forwarder.
CREATE TABLE dbo.FF_OCEAN_FREIGHT_HEADER (
    FQOH_Id             INT             NOT NULL IDENTITY(1,1),
    FQOH_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQOH_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQOH_START_DATE     DATE            NULL,
    FQOH_END_DATE       DATE            NULL,
    FQOH_REMARKS        NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_OCEAN_FREIGHT_HEADER   PRIMARY KEY CLUSTERED (FQOH_Id),
    CONSTRAINT UQ_FQOH_ForwarderQuote       UNIQUE (FQOH_FORWARDER, FQOH_QUOTENUMBER)
);
GO

CREATE INDEX IX_FQOH_Forwarder ON dbo.FF_OCEAN_FREIGHT_HEADER (FQOH_FORWARDER);
GO

-- Table 3: FF_OCEAN_FREIGHT_PORT
-- One row per port within a quote.
CREATE TABLE dbo.FF_OCEAN_FREIGHT_PORT (
    FQOP_Id             INT             NOT NULL IDENTITY(1,1),
    FQOP_Header_Id      INT             NOT NULL,
    FQOP_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQOP_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQOP_PORT           NVARCHAR(10)    NOT NULL,
    FQOP_REMARKS        NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_OCEAN_FREIGHT_PORT     PRIMARY KEY CLUSTERED (FQOP_Id),
    CONSTRAINT FK_FQOP_Header               FOREIGN KEY (FQOP_Header_Id)
        REFERENCES dbo.FF_OCEAN_FREIGHT_HEADER (FQOH_Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_FQOP_Header ON dbo.FF_OCEAN_FREIGHT_PORT (FQOP_Header_Id);
GO

-- Table 4: FF_OCEAN_FREIGHT_PORT_SLINE
-- One row per shipping line per port.
CREATE TABLE dbo.FF_OCEAN_FREIGHT_PORT_SLINE (
    FQOPL_Id            INT             NOT NULL IDENTITY(1,1),
    FQOPL_Port_Id       INT             NOT NULL,
    FQOPL_FORWARDER     NVARCHAR(10)    NOT NULL,
    FQOPL_QUOTENUMBER   NVARCHAR(10)    NOT NULL,
    FQOPL_PORT          NVARCHAR(10)    NOT NULL,
    FQOPL_SHIPLINE      NVARCHAR(10)    NOT NULL,
    FQOPL_ROUTE         NVARCHAR(15)    NULL,
    FQOPL_DAYS          SMALLINT        NULL,
    FQOPL_REMARKS       NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_OCEAN_FREIGHT_PORT_SLINE   PRIMARY KEY CLUSTERED (FQOPL_Id),
    CONSTRAINT FK_FQOPL_Port                    FOREIGN KEY (FQOPL_Port_Id)
        REFERENCES dbo.FF_OCEAN_FREIGHT_PORT (FQOP_Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_FQOPL_Port ON dbo.FF_OCEAN_FREIGHT_PORT_SLINE (FQOPL_Port_Id);
GO

-- Table 5: FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES
-- Charge amounts per container type per shipping line.
CREATE TABLE dbo.FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES (
    FQOPLC_Id               INT             NOT NULL IDENTITY(1,1),
    FQOPLC_SLine_Id         INT             NOT NULL,
    FQOPLC_FORWARDER        NVARCHAR(10)    NOT NULL,
    FQOPLC_QUOTENUMBER      NVARCHAR(10)    NOT NULL,
    FQOPLC_PORT             NVARCHAR(10)    NOT NULL,
    FQOPLC_SHIPLINE         NVARCHAR(10)    NOT NULL,
    FQOPLC_CHARGE_TYPE      NVARCHAR(6)     NOT NULL,
    FQOPLC_CONTAINER_TYPE   NVARCHAR(6)     NULL,
    FQOPLC_AMOUNT           DECIMAL(18,4)   NULL,
    FQOPLC_CURRENCY         NVARCHAR(3)     NULL,

    CONSTRAINT PK_FF_OCEAN_FREIGHT_CHARGES  PRIMARY KEY CLUSTERED (FQOPLC_Id),
    CONSTRAINT FK_FQOPLC_SLine              FOREIGN KEY (FQOPLC_SLine_Id)
        REFERENCES dbo.FF_OCEAN_FREIGHT_PORT_SLINE (FQOPL_Id) ON DELETE CASCADE
);
GO

CREATE INDEX IX_FQOPLC_SLine ON dbo.FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES (FQOPLC_SLine_Id);
GO

-- ============================================================
-- INLAND FREIGHT TABLES (4 levels)
-- ============================================================

-- Table 6: FF_INLAND_FREIGHT_HEADER
CREATE TABLE dbo.FF_INLAND_FREIGHT_HEADER (
    FQIH_Id             INT             NOT NULL IDENTITY(1,1),
    FQIH_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQIH_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQIH_START_DATE     DATE            NULL,
    FQIH_END_DATE       DATE            NULL,
    FQIH_REMARKS        NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_INLAND_FREIGHT_HEADER  PRIMARY KEY CLUSTERED (FQIH_Id),
    CONSTRAINT UQ_FQIH_ForwarderQuote       UNIQUE (FQIH_FORWARDER, FQIH_QUOTENUMBER)
);
GO

-- Table 7: FF_INLAND_FREIGHT_REGION
CREATE TABLE dbo.FF_INLAND_FREIGHT_REGION (
    FQIR_Id             INT             NOT NULL IDENTITY(1,1),
    FQIR_Header_Id      INT             NOT NULL,
    FQIR_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQIR_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQIR_REGION         NVARCHAR(20)    NOT NULL,

    CONSTRAINT PK_FF_INLAND_FREIGHT_REGION  PRIMARY KEY CLUSTERED (FQIR_Id),
    CONSTRAINT FK_FQIR_Header               FOREIGN KEY (FQIR_Header_Id)
        REFERENCES dbo.FF_INLAND_FREIGHT_HEADER (FQIH_Id) ON DELETE CASCADE
);
GO

-- Table 8: FF_INLAND_FREIGHT_REGION_TYPE
CREATE TABLE dbo.FF_INLAND_FREIGHT_REGION_TYPE (
    FQIRT_Id            INT             NOT NULL IDENTITY(1,1),
    FQIRT_Region_Id     INT             NOT NULL,
    FQIRT_FORWARDER     NVARCHAR(10)    NOT NULL,
    FQIRT_QUOTENUMBER   NVARCHAR(10)    NOT NULL,
    FQIRT_REGION        NVARCHAR(20)    NOT NULL,
    FQIRT_CHARGE_TYPE   NVARCHAR(6)     NOT NULL,
    FQIRT_AMOUNT_MIN    DECIMAL(18,4)   NULL,
    FQIRT_AMOUNT_MAX    DECIMAL(18,4)   NULL,
    FQIRT_CURRENCY      NVARCHAR(3)     NULL,

    CONSTRAINT PK_FF_INLAND_REGION_TYPE     PRIMARY KEY CLUSTERED (FQIRT_Id),
    CONSTRAINT FK_FQIRT_Region              FOREIGN KEY (FQIRT_Region_Id)
        REFERENCES dbo.FF_INLAND_FREIGHT_REGION (FQIR_Id) ON DELETE CASCADE
);
GO

-- Table 9: FF_INLAND_FREIGHT_REGION_TYPE_DET
CREATE TABLE dbo.FF_INLAND_FREIGHT_REGION_TYPE_DET (
    FQIRTD_Id               INT             NOT NULL IDENTITY(1,1),
    FQIRTD_RegionType_Id    INT             NOT NULL,
    FQIRTD_FORWARDER        NVARCHAR(10)    NOT NULL,
    FQIRTD_QUOTENUMBER      NVARCHAR(10)    NOT NULL,
    FQIRTD_REGION           NVARCHAR(20)    NOT NULL,
    FQIRTD_CHARGE_TYPE      NVARCHAR(6)     NOT NULL,
    FQIRTD_FROM             DECIMAL(18,4)   NULL,
    FQIRTD_TO               DECIMAL(18,4)   NULL,
    FQIRTD_PRICE            DECIMAL(18,4)   NULL,
    FQIRTD_PRICE_TYPE       NVARCHAR(6)     NULL,
    FQIRTD_AMOUNT_MIN       DECIMAL(18,4)   NULL,
    FQIRTD_AMOUNT_MAX       DECIMAL(18,4)   NULL,

    CONSTRAINT PK_FF_INLAND_REGION_TYPE_DET PRIMARY KEY CLUSTERED (FQIRTD_Id),
    CONSTRAINT FK_FQIRTD_RegionType         FOREIGN KEY (FQIRTD_RegionType_Id)
        REFERENCES dbo.FF_INLAND_FREIGHT_REGION_TYPE (FQIRT_Id) ON DELETE CASCADE
);
GO

-- ============================================================
-- LCL TABLES (4 levels)
-- ============================================================

-- Table 10: FF_LCL_HEADER
CREATE TABLE dbo.FF_LCL_HEADER (
    FQLH_Id             INT             NOT NULL IDENTITY(1,1),
    FQLH_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQLH_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQLH_START_DATE     DATE            NULL,
    FQLH_END_DATE       DATE            NULL,
    FQLH_REMARKS        NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_LCL_HEADER         PRIMARY KEY CLUSTERED (FQLH_Id),
    CONSTRAINT UQ_FQLH_ForwarderQuote   UNIQUE (FQLH_FORWARDER, FQLH_QUOTENUMBER)
);
GO

-- Table 11: FF_LCL_PORT
CREATE TABLE dbo.FF_LCL_PORT (
    FQLP_Id             INT             NOT NULL IDENTITY(1,1),
    FQLP_Header_Id      INT             NOT NULL,
    FQLP_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQLP_QUOTENUMBER    NVARCHAR(10)    NOT NULL,
    FQLP_PORT           NVARCHAR(10)    NOT NULL,
    FQLP_REMARKS        NVARCHAR(200)   NULL,

    CONSTRAINT PK_FF_LCL_PORT   PRIMARY KEY CLUSTERED (FQLP_Id),
    CONSTRAINT FK_FQLP_Header   FOREIGN KEY (FQLP_Header_Id)
        REFERENCES dbo.FF_LCL_HEADER (FQLH_Id) ON DELETE CASCADE
);
GO

-- Table 12: FF_LCL_PORT_TYPE
CREATE TABLE dbo.FF_LCL_PORT_TYPE (
    FQLPT_Id            INT             NOT NULL IDENTITY(1,1),
    FQLPT_Port_Id       INT             NOT NULL,
    FQLPT_FORWARDER     NVARCHAR(10)    NOT NULL,
    FQLPT_QUOTENUMBER   NVARCHAR(10)    NOT NULL,
    FQLPT_PORT          NVARCHAR(10)    NOT NULL,
    FQLPT_CHARGE_TYPE   NVARCHAR(6)     NOT NULL,
    FQLPT_AMOUNT_MIN    DECIMAL(18,4)   NULL,
    FQLPT_AMOUNT_MAX    DECIMAL(18,4)   NULL,
    FQLPT_CURRENCY      NVARCHAR(3)     NULL,

    CONSTRAINT PK_FF_LCL_PORT_TYPE  PRIMARY KEY CLUSTERED (FQLPT_Id),
    CONSTRAINT FK_FQLPT_Port        FOREIGN KEY (FQLPT_Port_Id)
        REFERENCES dbo.FF_LCL_PORT (FQLP_Id) ON DELETE CASCADE
);
GO

-- Table 13: FF_LCL_PORT_TYPE_DET
CREATE TABLE dbo.FF_LCL_PORT_TYPE_DET (
    FQLPTD_Id               INT             NOT NULL IDENTITY(1,1),
    FQLPTD_PortType_Id      INT             NOT NULL,
    FQLPTD_FORWARDER        NVARCHAR(10)    NOT NULL,
    FQLPTD_QUOTENUMBER      NVARCHAR(10)    NOT NULL,
    FQLPTD_PORT             NVARCHAR(10)    NOT NULL,
    FQLPTD_CHARGE_TYPE      NVARCHAR(6)     NOT NULL,
    FQLPTD_FROM             DECIMAL(18,4)   NULL,
    FQLPTD_TO               DECIMAL(18,4)   NULL,
    FQLPTD_PRICE            DECIMAL(18,4)   NULL,
    FQLPTD_OVER             DECIMAL(18,4)   NULL,
    FQLPTD_PRICE_TYPE       NVARCHAR(6)     NULL,
    FQLPTD_AMOUNT_MIN       DECIMAL(18,4)   NULL,
    FQLPTD_AMOUNT_MAX       DECIMAL(18,4)   NULL,

    CONSTRAINT PK_FF_LCL_PORT_TYPE_DET  PRIMARY KEY CLUSTERED (FQLPTD_Id),
    CONSTRAINT FK_FQLPTD_PortType       FOREIGN KEY (FQLPTD_PortType_Id)
        REFERENCES dbo.FF_LCL_PORT_TYPE (FQLPT_Id) ON DELETE CASCADE
);
GO

-- ============================================================
-- Table 14: FF_INLAND_ADDITIONAL_CHARGES
-- Per-forwarder flat charges (no quote number needed).
-- ============================================================
CREATE TABLE dbo.FF_INLAND_ADDITIONAL_CHARGES (
    FQIA_Id             INT             NOT NULL IDENTITY(1,1),
    FQIA_FORWARDER      NVARCHAR(10)    NOT NULL,
    FQIA_CHARGE_TYPE    NVARCHAR(6)     NOT NULL,
    FQIA_LOADTYPE       NVARCHAR(6)     NULL,
    FQIA_AMOUNT         DECIMAL(18,4)   NULL,
    FQIA_ACTION         NVARCHAR(6)     NULL,
    FQIA_CHARGE_OVER    NVARCHAR(6)     NULL,
    FQIA_CHARGE_PER     NVARCHAR(6)     NULL,
    FQIA_FROM           DECIMAL(18,4)   NULL,
    FQIA_TO             DECIMAL(18,4)   NULL,
    FQIA_AMOUNT_MIN     DECIMAL(18,4)   NULL,
    FQIA_AMOUNT_MAX     DECIMAL(18,4)   NULL,
    FQIA_CURRENCY       NVARCHAR(3)     NULL,

    CONSTRAINT PK_FF_INLAND_ADDITIONAL_CHARGES PRIMARY KEY CLUSTERED (FQIA_Id)
);
GO

CREATE INDEX IX_FQIA_Forwarder ON dbo.FF_INLAND_ADDITIONAL_CHARGES (FQIA_FORWARDER);
GO

-- ============================================================
-- Verification
-- ============================================================
SELECT t.name AS TableName, COUNT(c.column_id) AS Columns
FROM sys.tables t
JOIN sys.columns c ON c.object_id = t.object_id
WHERE t.name IN (
    'FREIGHT_FORWARDERS',
    'FF_OCEAN_FREIGHT_HEADER','FF_OCEAN_FREIGHT_PORT',
    'FF_OCEAN_FREIGHT_PORT_SLINE','FF_OCEAN_FREIGHT_PORT_SLINE_CHARGES',
    'FF_INLAND_FREIGHT_HEADER','FF_INLAND_FREIGHT_REGION',
    'FF_INLAND_FREIGHT_REGION_TYPE','FF_INLAND_FREIGHT_REGION_TYPE_DET',
    'FF_LCL_HEADER','FF_LCL_PORT','FF_LCL_PORT_TYPE','FF_LCL_PORT_TYPE_DET',
    'FF_INLAND_ADDITIONAL_CHARGES'
)
GROUP BY t.name
ORDER BY t.name;
GO

PRINT '✓ Freight Forwarder main & quote tables created in LicoresMaduoDB.';
GO
